<a href="https://colab.research.google.com/github/Slh62804/medical-rag-assistant/blob/main/Natural_Language_Processing_with_Generative_AI_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1><center></center></h1>
<h1><center><font size=10>Natural Language Processing with Generative AI Project</center></font></h1>
<h1><center>Medical Assistant</center></h1>

##**Business Context**

The healthcare industry is rapidly evolving, with professionals facing increasing challenges in managing vast volumes of medical data while delivering accurate and timely diagnoses. The need for quick access to comprehensive, reliable, and up-to-date medical knowledge is critical for improving patient outcomes and ensuring informed decision-making in a fast-paced environment.

Healthcare professionals often encounter information overload, struggling to sift through extensive research and data to create accurate diagnoses and treatment plans. This challenge is amplified by the need for efficiency, particularly in emergencies, where time-sensitive decisions are vital. Furthermore, access to trusted, current medical information from renowned manuals and research papers is essential for maintaining high standards of care.

To address these challenges, healthcare centers can focus on integrating systems that streamline access to medical knowledge, provide tools to support quick decision-making, and enhance efficiency. Leveraging centralized knowledge platforms and ensuring healthcare providers have continuous access to reliable resources can significantly improve patient care and operational effectiveness.

##**Objective**

As an AI specialist, your task is to develop a RAG-based AI solution using renowned medical manuals to address healthcare challenges. The objective is to understand information overload, apply AI techniques to streamline decision-making, analyze its impact on diagnostics and patient outcomes, evaluate its potential to standardize care practices, and create a functional prototype demonstrating its feasibility and effectiveness.

**Questions to Answer**

1.  What is the protocol for managing sepsis in a critical care unit?


2.  What are the common symptoms of appendicitis, and can it be cured via medicine? If not, what surgical procedure should be followed to treat it?


3.  What are the effective treatments or solutions for addressing sudden patchy hair loss, commonly seen as localized bald spots on the scalp, and what could be the possible causes behind it?


4.  What treatments are recommended for a person who has sustained a physical injury to brain tissue, resulting in temporary or permanent impairment of brain function?


5.  What are the necessary precautions and treatment steps for a person who has fractured their leg during a hiking trip, and what should be considered for their care and recovery?

##**Data Dictionary**


The Merck Manuals are medical references published by the American pharmaceutical company Merck & Co., that cover a wide range of medical topics, including disorders, tests, diagnoses, and drugs. The manuals have been published since 1899 when Merck & Co. was still a subsidiary of the German company Merck.

The manual is a PDF with over 4,000 pages divided into 23 sections.

**Installing and Importing Necessary Libraries and Dependencies**

In [ ]:
!CMAKE_ARGS="-DLLAMA_CUBLAS=on" FORCE_CMAKE=1 pip install llama-cpp-python==0.1.85 --force-reinstall --no-cache-dir -q

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 42.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.5/45.5 kB 285.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.7/16.7 MB 254.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.6/45.6 kB 296.0 MB/s eta 0:00:00
  Building wheel for llama-cpp-python (pyproject.toml) ... done
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
chromadb 0.5.5 requires numpy<2.0.0,>=1.22.5, but you have numpy 2.5.2 which is incompatible.
numba 0.61.2 requires numpy<2.3,>=1.24, but you have numpy 2.5.2 which is incompatible.
langgraph-sdk 0.4.2 requires langchain-core<2,>=1.4.0, but you have langchain-core 0.3.86 which is incompatible.
gradio 6.24.0 requires huggingface-hub<2.0,>=1.16.0, but you have huggingface-hub 0.36.2 which is incompatible.
langgraph-prebuilt 1.1.0 requires langchain-core>=1.3.1, but you have langchain-core 0.3.86 which is incompatible.
google-adk 2.7.1 requires opentelemetry-api<=1.42.1,>=1.39, but you have opentelemetry-api 1.44.0 which is incompatible.
google-adk 2.7.1 requires opentelemetry-sdk<=1.42.1,>=1.39, but you have opentelemetry-sdk 1.44.0 which is incompatible.
langgraph 1.2.11 requires langchain-core<2,>=1.4.7, but you have langchain-core 0.3.86 which is incompatible.

In [ ]:
!pip install -q \
    huggingface_hub>=0.25.0 \
    pandas>=2.2.2 \
    tiktoken \
    pymupdf==1.25.1 \
    langchain \
    langchain-community \
    langchain-text-splitters==0.3.6 \
    chromadb==0.5.5 \
    sentence-transformers==3.2.0 \
    numpy

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ml-dtypes 0.6.0 requires numpy>=2.0.0, but you have numpy 1.26.4 which is incompatible.
ml-dtypes 0.6.0 requires numpy>=2.1.0; python_version >= "3.13", but you have numpy 1.26.4 which is incompatible.
jaxlib 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
shap 0.52.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
gradio 6.24.0 requires huggingface-hub<2.0,>=1.16.0, but you have huggingface-hub 0.36.2 which is incompatible.
xarray-einstats 0.11.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-contrib-python 4.14.0.94 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
dm-tree 0.1.10 requires numpy>=2.1.0; python_version >= "3.13", but you have numpy 1.26.4 which is incompatible.
rasterio 1.5.1 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
tifffile 2026.8.16 requires numpy>=2.1, but you have numpy 1.26.4 which is incompatible.
opencv-python 5.0.0.93 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
pytensor 2.38.3 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
jax 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
cupy-cuda12x 14.0.1 requires numpy<2.6,>=2.0, but you have numpy 1.26.4 which is incompatible.
tobler 0.14.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-python-headless 5.0.0.93 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.

In [ ]:
#Libraries for processing dataframes,text
import json,os
import tiktoken
import pandas as pd

#Libraries for Loading Data, Chunking, Embedding, and Vector Databases
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_community.document_loaders import PyMuPDFLoader
from langchain_community.embeddings.sentence_transformer import SentenceTransformerEmbeddings
from langchain_community.vectorstores import Chroma

from huggingface_hub import hf_hub_download
from llama_cpp import Llama

##Question Answering using LLM

###Downloading and Loading the model

In [ ]:
# Download the Mistral 7B Instruct v0.2 GGUF model from Hugging Face.
# Q4_K_M provides a good balance between model size and response quality.

model_name = "TheBloke/Mistral-7B-Instruct-v0.2-GGUF"
model_file = "mistral-7b-instruct-v0.2.Q4_K_M.gguf"

model_path = hf_hub_download(
    repo_id=model_name,
    filename=model_file
)

print("Model downloaded successfully.")
print("Model path:", model_path)

/usr/local/lib/python3.13/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

mistral-7b-instruct-v0.2.Q4_K_M.gguf:   0%|          | 0.00/4.37G [00:00<?, ?B/s]

Model downloaded successfully.
Model path: /root/.cache/huggingface/hub/models--TheBloke--Mistral-7B-Instruct-v0.2-GGUF/snapshots/3a6fbf4a41a1d52e415a4958cde6856d34b2db93/mistral-7b-instruct-v0.2.Q4_K_M.gguf

In [ ]:
# Load the downloaded Mistral model using llama.cpp.
# n_ctx defines the context window.
# n_gpu_layers=-1 attempts to offload the model layers to the GPU.

llm = Llama(
    model_path=model_path,
    n_ctx=4096,
    n_gpu_layers=-1,
    verbose=True
)

print("Mistral 7B Instruct model loaded successfully.")

Mistral 7B Instruct model loaded successfully.

AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 |

###**Response**

In [ ]:
def response(query,max_tokens=128,temperature=0,top_p=0.95,top_k=50):
    model_output = llm(
      prompt=query,
      max_tokens=max_tokens,
      temperature=temperature,
      top_p=top_p,
      top_k=top_k
    )

    return model_output['choices'][0]['text']

`  Query 1: What is the protocol for managing sepsis in a critical care unit?`

In [ ]:
query_1 = """[INST]
What is the protocol for managing sepsis in a critical care unit?
[/INST]"""

response_1 = response(
    query_1,
    max_tokens=300,
    temperature=0,
    top_p=0.95,
    top_k=50
)

print(response_1)

 Sepsis is a life-threatening condition caused by the body's response to an infection, and managing it effectively in a critical care unit requires a multidisciplinary approach. Here are some key steps in the protocol for managing sepsis in a critical care unit:
1. Early recognition and diagnosis: Identify sepsis early by recognizing the signs and symptoms, such as fever or hypothermia, tachycardia or bradycardia, altered mental status, and lactic acidosis. Use the Sequential Organ Failure Assessment (SOFA) score to assess organ dysfunction.
2. Resuscitation: Provide fluid resuscitation to maintain adequate tissue perfusion and oxygenation. Aim for a mean arterial pressure of 65 mmHg or higher and a central venous oxygen saturation of 70% or higher.
3. Antibiotics: Administer broad-spectrum antibiotics as soon as possible based on culture results, clinical suspicion, and local guidelines.
4. Source control: Identify and address the source of infection, such as drainage of abscesses or debridement of necrotic tissue.
5. Vasopressors: Use vasopressors to maintain adequate blood pressure if fluid resuscitation is not sufficient.
6. Corticosteroids: Consider using corticosteroids in certain

**Observation:**

The baseline LLM outlines sepsis management—stabilization, fluids, antimicrobials, hemodynamic support, and monitoring. However, since it is not yet linked to the Merck Manuals, the response cannot be traced to the designated source. It should be treated only as a preliminary benchmark for later RAG-based outputs.

`Query 2: What are the common symptoms for appendicitis, and can it be cured via medicine? If not, what surgical procedure should be followed to treat it?`

In [ ]:
query_2 = """[INST]
What are the common symptoms for appendicitis, and can it be cured via medicine?
If not, what surgical procedure should be followed to treat it?
[/INST]"""

response_2 = response(
    query_2,
    max_tokens=300,
    temperature=0,
    top_p=0.95,
    top_k=50
)

print(response_2)

Llama.generate: prefix-match hit

 Appendicitis is a medical condition characterized by inflammation of the appendix, a small tube-shaped organ located in the lower right side of the abdomen. The following are common symptoms of appendicitis:
1. Abdominal pain, usually starting around the navel and then shifting to the lower right side
2. Loss of appetite
3. Nausea and vomiting
4. Fever
5. Diarrhea or constipation
6. Abdominal swelling
7. Inability to pass gas or have a bowel movement
8. Feeling bloated or full
9. Pain upon walking, coughing, or moving
10. Anxiety and restlessness
Appendicitis cannot be cured via medicine alone as the inflammation can cause the appendix to rupture, leading to peritonitis, a serious infection of the abdominal cavity. If left untreated, it can be life-threatening. Therefore, if you suspect appendicitis, it is essential to seek medical attention immediately.
The standard treatment for appendicitis is surgical removal of the appendix, known as an appendectomy. This procedure can be performed through open surgery or laparoscopically, depending on the severity and location of the inflammation. The goal of the surgery is to remove the infected appendix before it ruptures and spreads infection

**Observation:**

The LLM should identify common manifestations of appendicitis and discuss medical management and appendectomy. The response demonstrates that a general-purpose LLM can provide useful medical information, but it does not provide evidence that the information is derived from the Merck Manuals. This limitation motivates the use of RAG

`Query 3: What are the effective treatments or solutions for addressing sudden patchy hair loss, commonly seen as localized bald spots on the scalp, and what could be the possible causes behind it?`

In [ ]:
query_3 = """[INST]
What are the effective treatments or solutions for addressing sudden patchy hair loss,
commonly seen as localized bald spots on the scalp, and what could be the possible
causes behind it?
[/INST]"""

response_3 = response(
    query_3,
    max_tokens=350,
    temperature=0,
    top_p=0.95,
    top_k=50
)

print(response_3)

Llama.generate: prefix-match hit

 Sudden patchy hair loss, also known as alopecia areata, is an autoimmune condition that causes hair loss in small patches on the scalp, beard, or other areas of the body. The exact cause of alopecia areata is not known, but it's believed to be related to a problem with the immune system. Here are some effective treatments and solutions for addressing sudden patchy hair loss:
1. Topical corticosteroids: These are anti-inflammatory medications that can help reduce inflammation and promote hair growth. They can be applied directly to the affected area in the form of creams, lotions, or solutions.
2. Injections of corticosteroids: In some cases, corticosteroids may be injected directly into the bald spots to promote hair growth. This treatment is usually reserved for severe cases of alopecia areata.
3. Minoxidil: This medication is applied topically and has been shown to help slow down hair loss and promote new hair growth in some people with alopecia areata.
4. DHT blockers: Dihydrotestosterone (DHT) is a hormone that can contribute to hair loss. Some people with alopecia areata may benefit from using DHT blockers, such as finasteride or dutasteride.
5. Immune system modulators: In some cases, medications that modify the immune system may be prescribed to help reduce inflammation and promote hair growth.
6. Wigs or hairpieces: If hair loss is extensive or not responding to treatment, wigs or hairpieces

**Observation:**

 The response is expected to discuss possible causes of localized hair loss, including alopecia areata and other differential diagnoses, together with treatment approaches. However, the baseline model may provide a broad answer without clearly distinguishing which information is supported by the project's reference manual.

`Query 4: What treatments are recommended for a person who has sustained a physical injury to brain tissue, resulting in temporary or permanent impairment of brain function?`

In [ ]:
query_4 = """[INST]
What treatments are recommended for a person who has sustained a physical injury
to brain tissue, resulting in temporary or permanent impairment of brain function?
[/INST]"""

response_4 = response(
    query_4,
    max_tokens=350,
    temperature=0,
    top_p=0.95,
    top_k=50
)

print(response_4)

Llama.generate: prefix-match hit

 A person who has sustained a physical injury to the brain, also known as a traumatic brain injury (TBI), may require various treatments depending on the severity and location of the injury. Here are some common treatments recommended for TBIs:
1. Medical Management: This includes addressing any life-threatening conditions such as airway obstruction, breathing problems, or excessive bleeding.
2. Surgical Intervention: In some cases, surgery may be necessary to remove hematomas (clots) or decompress the skull to relieve pressure on the brain.
3. Rehabilitation: Rehabilitation is an essential part of treatment for TBIs. It may include physical therapy to help with mobility and strength, occupational therapy to help with daily living activities, speech therapy to improve communication skills, and cognitive rehabilitation to address memory, attention, and problem-solving abilities.
4. Medications: Depending on the symptoms, medications may be prescribed to manage conditions such as seizures, pain, or depression.
5. Nutritional Support: Proper nutrition is essential for brain function and recovery. A person with a TBI may require nutritional support through a feeding tube or intravenous fluids if they are unable to eat or drink on their own.
6. Assistive Devices: Assistive devices such as wheelchairs, walkers, or communication aids may be necessary to help the person function optimally and safely.
7. Support Groups: Joining support groups can provide emotional and social support for individuals with TBIs and their families.
8. Lifestyle Modifications: Making lifestyle modifications such

**Observation:**

The model provides a general description of traumatic brain injury management, potentially including stabilization, neurological assessment, management of intracranial complications and rehabilitation. The main limitation is again the lack of source grounding and traceability.

`Query 5: What are the necessary precautions and treatment steps for a person who has fractured their leg during a hiking trip, and what should be considered for their care and recovery?`

In [ ]:
query_5 = """[INST]
What are the necessary precautions and treatment steps for a person who has fractured
their leg during a hiking trip, and what should be considered for their care and recovery?
[/INST]"""

response_5 = response(
    query_5,
    max_tokens=350,
    temperature=0,
    top_p=0.95,
    top_k=50
)

print(response_5)

Llama.generate: prefix-match hit

 If a person has fractured their leg during a hiking trip, it is important that they take the following necessary precautions and seek medical attention as soon as possible:
1. Stay calm and try to prevent further injury: Encourage the person to remain still and avoid moving the injured leg as much as possible to prevent further damage or discomfort.
2. Apply ice: Apply an ice pack to the injured area for 15-20 minutes at a time, several times a day, to help reduce swelling and pain.
3. Elevate the leg: Try to keep the injured leg elevated above heart level as much as possible to help reduce swelling and promote blood flow.
4. Immobilize the leg: Use a splint, sling, or brace to immobilize the leg and prevent any movement that could cause further damage.
5. Seek medical attention: It is important to seek medical attention as soon as possible for proper diagnosis and treatment of the fracture. The healthcare professional may recommend immobilization with a cast or brace, pain management, and physical therapy to help promote healing and restore mobility.
6. Consider transportation: Depending on the location and severity of the injury, it may be necessary to arrange for transportation to the nearest medical facility. If the person is unable to walk, they may need to be carried out on a stretcher or evacuated by helicopter or other means.
7. Provide emotional support: Being injured can be a stressful and overwhelming experience, so it's important to provide emotional support and reassurance to the person while they are recovering. Encourage them to ask questions and express their concerns

**Observation:**

The model should provide information about immobilization, emergency assessment, fracture management, possible complications and recovery. Since this is an emergency/injury scenario, the response should emphasize professional medical assessment. The baseline answer does not provide a reliable source trail to the Merck Manuals.

##**Question Answering using LLM with Prompt Engineering**

For this section, we need at least five combinations.

Rather than manually creating five separate functions, create one reusable function and five parameter configurations

In [ ]:
def generate_prompt_response(
    question,
    system_instruction,
    max_tokens=300,
    temperature=0,
    top_p=0.95,
    top_k=50
):

    prompt = f"""[INST]
{system_instruction}

Question:
{question}
[/INST]"""

    model_output = llm(
        prompt=prompt,
        max_tokens=max_tokens,
        temperature=temperature,
        top_p=top_p,
        top_k=top_k
    )

    return model_output["choices"][0]["text"].strip()

###**Define 5 Combinations**

In [ ]:
prompt_configurations = [

    {
        "name": "Configuration 1 - Basic",
        "instruction": """
Answer the medical question clearly and concisely.
Provide the important symptoms, causes and treatments where applicable.
""",
        "temperature": 0,
        "top_p": 0.95,
        "top_k": 50,
        "max_tokens": 300
    },

    {
        "name": "Configuration 2 - Structured",
        "instruction": """
Answer the medical question using the following structure:
1. Key symptoms/findings
2. Possible causes or diagnosis
3. Treatment/management
4. Important precautions
Keep the answer concise and factual.
""",
        "temperature": 0.2,
        "top_p": 0.9,
        "top_k": 40,
        "max_tokens": 350
    },

    {
        "name": "Configuration 3 - Clinical",
        "instruction": """
Act as a medical information assistant.
Provide a clinically organized answer.
Clearly distinguish symptoms, diagnosis, treatment and complications.
Avoid unsupported claims.
""",
        "temperature": 0.2,
        "top_p": 0.85,
        "top_k": 40,
        "max_tokens": 400
    },

    {
        "name": "Configuration 4 - Conservative",
        "instruction": """
Provide a cautious, evidence-oriented medical response.
Do not invent information.
If there is uncertainty, explicitly mention it.
Focus on clinically important information.
""",
        "temperature": 0,
        "top_p": 0.8,
        "top_k": 30,
        "max_tokens": 400
    },

    {
        "name": "Configuration 5 - Detailed",
        "instruction": """
Provide a comprehensive medical response covering:
symptoms, possible causes, diagnosis, treatment, complications,
precautions and relevant emergency considerations.
Use clear headings and avoid unnecessary repetition.
""",
        "temperature": 0.3,
        "top_p": 0.9,
        "top_k": 50,
        "max_tokens": 500
    }
]

`Query 1: What is the protocol for managing sepsis in a critical care unit? (With all 5 combinations)`

In [ ]:
for config in prompt_configurations:

    print("=" * 100)
    print(config["name"])
    print("=" * 100)

    answer = generate_prompt_response(
        question=query_1.replace("[INST]", "").replace("[/INST]", ""),
        system_instruction=config["instruction"],
        max_tokens=config["max_tokens"],
        temperature=config["temperature"],
        top_p=config["top_p"],
        top_k=config["top_k"]
    )

    print(answer)

====================================================================================================
Configuration 1 - Basic
====================================================================================================

Llama.generate: prefix-match hit

Sepsis is a life-threatening condition caused by the body's response to an infection. In a critical care unit, managing sepsis involves the following steps:

1. Recognition and early identification: Identify patients with suspected infection and assess for signs of sepsis, such as fever or hypothermia, tachycardia or bradycardia, respiratory distress, altered mental status, and lactic acidosis.
2. Immediate fluid resuscitation: Administer intravenous fluids to maintain adequate blood pressure and organ perfusion. The goal is to achieve a mean arterial pressure (MAP) of 65 mmHg or higher.
3. Antibiotics: Start broad-spectrum antibiotics as soon as possible, based on the suspected infection site and microbiological cultures if available.
4. Source control: Identify and address the source of infection, such as removing an infected catheter or draining an abscess.
5. Vasopressors: If fluid resuscitation fails to maintain adequate blood pressure, administer vasopressors to support blood pressure and organ perfusion.
6. Corticosteroids: Consider using corticosteroids in certain situations, such as septic shock or ARDS, but only after consulting with a critical care specialist.
7. Inotropes: Use inotropes
====================================================================================================
Configuration 2 - Structured
====================================================================================================

Llama.generate: prefix-match hit

1. Key symptoms/findings: Sepsis is a life-threatening condition caused by the body's response to infection. Symptoms may include fever, chills, rapid heart rate, rapid breathing, low blood pressure, confusion or disorientation, and decreased urine output. In severe cases, septic shock can occur, leading to organ failure.
2. Possible causes or diagnosis: Sepsis is usually caused by bacterial infections, most commonly from the lungs (pneumonia), urinary tract, or abdomen. Diagnosis is based on clinical signs and laboratory findings, such as high white blood cell count, elevated lactate levels, and low oxygen levels in the blood.
3. Treatment/management: Early recognition and prompt treatment are crucial for improving outcomes. This includes administering antibiotics to address the underlying infection, providing intravenous fluids to maintain adequate blood pressure, and providing oxygen support if necessary. In some cases, vasopressors may be needed to maintain blood pressure.
4. Important precautions: Sepsis can quickly progress to septic shock, which can lead to organ failure and death. Close monitoring in a critical care unit is essential. Early recognition and prompt treatment are crucial for improving outcomes. Additionally, preventing infections through good hygiene practices and vaccinations can help prevent sepsis.
====================================================================================================
Configuration 3 - Clinical
====================================================================================================

Llama.generate: prefix-match hit

Sepsis is a life-threatening condition caused by the body's response to an infection. In a critical care unit, managing sepsis requires a swift and coordinated approach to prevent progression to septic shock. Here's a clinically organized answer:

1. Recognition of symptoms:
   * Fever or hypothermia
   * Tachycardia (heart rate >90 bpm) or bradycardia (<60 bpm)
   * Respiratory distress (tachypnea, dyspnea, or altered respiratory status)
   * Altered mental status
   * Decreased urine output
   * Hematologic abnormalities (leukocytosis or leukopenia, thrombocytopenia)
   * Lactic acidosis

2. Diagnosis:
   * Suspected infection and positive blood culture or other microbiological evidence
   * Clinical assessment using Sequential [Sepsis-related] Organ Failure Assessment (SOFA) score

3. Immediate treatment:
   * Oxygen therapy to maintain adequate oxygenation
   * Intravenous fluids to maintain adequate blood pressure and organ perfusion
   * Broad-spectrum antibiotics based on suspected infection and microbiological results
   * Vasopressors if needed for hypotension
   * Corticosteroids in specific cases (septic shock, ARDS)
   * Inotropes to support cardiac output

4. Complications:
   * Cardiovascular: arrhythmias, myocardial dysfunction, vasopressor-dependent hypertension
   * Respiratory: acute respiratory distress syndrome (ARDS), acute lung injury (ALI)
   * Renal
====================================================================================================
Configuration 4 - Conservative
====================================================================================================

Llama.generate: prefix-match hit

Sepsis is a life-threatening condition caused by the body's response to infection. In a critical care unit, managing sepsis involves a swift and coordinated approach to address the underlying infection, support organ function, and prevent complications. Here are some key steps in sepsis management based on current clinical guidelines:

1. Early recognition and diagnosis: Recognize sepsis early by assessing for signs of infection and systemic inflammatory response. Use validated scoring systems like the Sequential Organ Failure Assessment (SOFA) or Quick Sequential [Sepsis-related] Organ Failure Assessment (qSOFA) to help identify patients at risk.

2. Fluid resuscitation: Aim for adequate tissue perfusion by administering intravenous fluids to maintain mean arterial pressure ≥65 mmHg and central venous oxygen saturation >70%. Use crystalloids initially, followed by colloids or blood products if needed.

3. Antibiotics: Administer broad-spectrum antibiotics as soon as possible based on suspected infection site and microbiological cultures if available.

4. Source control: Identify and address the source of infection whenever possible. This may include surgical intervention, drainage, or debridement.

5. Vasopressors and inotropes: If sepsis-induced hypotension is refractory to fluid resuscitation, consider using vasopressors and/or inotropes to maintain adequate blood pressure and organ perfusion.

6. Corticosteroids: In some cases, corticosteroids may be considered for patients with septic shock who do not respond to initial fluid resuscitation and vasopressor therapy.

7. Other supportive measures: Provide appropriate oxygenation and ventilation support,
====================================================================================================
Configuration 5 - Detailed
====================================================================================================

Llama.generate: prefix-match hit

Title: Sepsis Management Protocol in a Critical Care Unit

1. Symptoms:
Sepsis is a life-threatening condition caused by the body's response to an infection, which can lead to tissue damage and organ failure. Common symptoms include fever or hypothermia, rapid heart rate, rapid breathing, confusion or disorientation, low blood pressure, and decreased urine output. In severe cases, septic shock may occur, leading to further complications such as multi-organ failure.

2. Possible Causes:
Sepsis can be caused by various types of infections, including bacterial, viral, fungal, or parasitic infections. The most common sources are respiratory tract infections (pneumonia), urinary tract infections, and intra-abdominal infections.

3. Diagnosis:
The diagnosis of sepsis is based on clinical evaluation, laboratory findings, and imaging studies. The Sequential [Sepsis-related] Organ Failure Assessment (SOFA) score can help identify patients at risk for developing sepsis. A positive blood culture is not always required for the diagnosis, as up to 30% of septic patients may have negative cultures.

4. Treatment:
The primary goal in managing sepsis in a critical care unit is to address the underlying infection and support organ function. This includes administering appropriate antibiotics, providing adequate fluid resuscitation, maintaining adequate oxygenation and ventilation, and addressing any specific organ dysfunction. Early goal-directed therapy (EGDT) may be used to optimize hemodynamic parameters and improve outcomes.

5. Complications:
Complications of sepsis in a critical care unit can include multi-organ failure, septic shock, acute respiratory distress syndrome (ARDS), disseminated intravascular coagulation (DIC), and cardiac dysfunction. Close monitoring and prompt intervention are essential to prevent or minimize these complications.

6. Precautions:
In the critical care setting, sepsis patients should be placed in a private room with strict infection control measures in place. Healthcare personnel should practice standard precautions, including wearing personal protective equipment (PPE), and follow appropriate hand hygiene procedures.

7

`Query 2: What are the common symptoms for appendicitis, and can it be cured via medicine? If not, what surgical procedure should be followed to treat it?(With all 5 combinations)`

In [ ]:
for config in prompt_configurations:

    print("=" * 100)
    print(config["name"])
    print("=" * 100)

    answer = generate_prompt_response(
        question=query_2.replace("[INST]", "").replace("[/INST]", ""),
        system_instruction=config["instruction"],
        max_tokens=config["max_tokens"],
        temperature=config["temperature"],
        top_p=config["top_p"],
        top_k=config["top_k"]
    )

    print(answer)

====================================================================================================
Configuration 1 - Basic
====================================================================================================

Llama.generate: prefix-match hit

Appendicitis is a medical condition characterized by inflammation of the appendix, a small pouch located in the lower right side of the abdomen. Common symptoms include:

1. Sudden and persistent pain in the lower right abdomen, often starting as a mild discomfort that gradually worsens over hours.
2. Loss of appetite and feeling sick to your stomach (nausea).
3. Vomiting.
4. Fever, especially in higher temperatures (above 101 degrees Fahrenheit or 38 degrees Celsius).
5. Constipation or diarrhea.
6. Abdominal swelling and tenderness.
7. Inability to pass gas or have a bowel movement.

Appendicitis cannot be cured with medicine alone, as the inflammation can lead to the appendix rupturing if left untreated. If diagnosed early, antibiotics may help prevent complications during surgery. However, surgical removal of the appendix (appendectomy) is the standard treatment for appendicitis. This procedure can be performed laparoscopically or open, depending on the severity and individual circumstances.

It's essential to seek medical attention promptly if you suspect appendicitis, as a ruptured appendix can lead to severe complications like peritonitis, which can be life-threatening
====================================================================================================
Configuration 2 - Structured
====================================================================================================

Llama.generate: prefix-match hit

1. Key symptoms/findings:
- Sudden onset of pain in the lower right abdomen, often starting as a mild discomfort that gradually worsens over hours.
- Loss of appetite and feeling sick to your stomach (nausea).
- Vomiting.
- Fever and chills.
- Pain worsening with movement or pressure on the abdomen.
- Constipation or diarrhea.

2. Possible causes or diagnosis:
Appendicitis is most commonly caused by a blockage in the small, hollow organ located in the lower right side of the abdomen called the appendix. The blockage can be due to fecal matter, lymph, or mucus. If left untreated, the appendix can rupture, leading to peritonitis, a serious inflammation of the abdominal cavity. Diagnosis is typically made through physical examination and imaging tests such as ultrasound or CT scan.

3. Treatment/management:
Appendicitis cannot be cured with medicine alone. The standard treatment for appendicitis is surgical removal of the appendix, known as an appendectomy. This procedure can be performed laparoscopically (using small incisions and a camera) or open surgery (making a larger incision). Antibiotics may be given before or after surgery to prevent infection.

4. Important precautions:
If you suspect appendicitis, seek medical attention immediately as the condition can worsen quickly and lead to complications such as perforation and sepsis. Del
====================================================================================================
Configuration 3 - Clinical
====================================================================================================

Llama.generate: prefix-match hit

Appendicitis is a medical condition characterized by inflammation of the appendix, a small pouch located in the lower right side of the abdomen. The following are common symptoms of appendicitis:

1. Abdominal pain: This is usually the first and most prominent symptom. The pain may begin as a vague discomfort in the middle of the abdomen, but it soon localizes to the right lower quadrant. The pain worsens with movement or pressure on the area.
2. Loss of appetite: People with appendicitis often lose their appetite due to the abdominal pain and nausea.
3. Nausea and vomiting: Vomiting is a common symptom, especially in advanced cases.
4. Fever: A low-grade fever may be present.
5. Constipation or diarrhea: Both can occur, but constipation is more common.
6. Rebound tenderness: This is a sign of inflammation and is elicited by gently pressing on the abdomen and then releasing the pressure.
7. Guarding: This is the involuntary contraction of the abdominal muscles in response to pain.
8. Rigidity: The abdomen may feel rigid or hard to the touch.

Appendicitis cannot be cured with medicine alone. If left untreated, the appendix can rupture, leading to peritonitis, a potentially life-threatening condition. Therefore, surgery is the standard treatment for appendicitis. The surgical procedure typically involves removing the appendix through an incision in the abdomen (open appendectomy) or using laparoscopic techniques (laparoscopic appendectomy). Both procedures have their advantages and disadvantages, and the choice depends on various factors, including the severity of the condition and
====================================================================================================
Configuration 4 - Conservative
====================================================================================================

Llama.generate: prefix-match hit

Appendicitis is a medical condition characterized by inflammation of the appendix, a small tube-shaped organ located in the lower right abdomen. The symptoms of appendicitis can vary but typically include:

1. Abdominal pain, usually starting around the navel and then shifting to the right lower quadrant.
2. Loss of appetite.
3. Nausea and vomiting.
4. Fever.
5. Diarrhea or constipation.
6. Abdominal swelling and tenderness.
7. Pain upon walking or moving around.
8. Inability to pass gas or have a bowel movement.

It is important to note that these symptoms can also be present in other conditions, so a proper diagnosis should always be made by a healthcare professional.

Regarding the treatment for appendicitis, it is generally not curable with medicine alone. The standard treatment is surgical removal of the appendix, known as an appendectomy. This procedure is typically performed laparoscopically, which involves making small incisions and using a camera to guide the surgeon. Open appendectomy, where a larger incision is made, may be necessary in certain cases.

The goal of surgery is to remove the inflamed appendix before it ruptures, as a ruptured appendix can lead to complications such as peritonitis and sepsis. It's essential to seek medical attention promptly if you suspect appendicitis, as early treatment can improve outcomes and reduce the risk of complications.
====================================================================================================
Configuration 5 - Detailed
====================================================================================================

Llama.generate: prefix-match hit

**Appendicitis:** A Medical Condition Requiring Prompt Attention

**Symptoms:**
Appendicitis is an inflammatory condition of the appendix, a small tube-like structure attached to the large intestine. The symptoms may include:

1. Sudden and persistent pain in the lower right abdomen
2. Loss of appetite
3. Nausea and vomiting
4. Fever (often low-grade)
5. Abdominal swelling
6. Constipation or diarrhea
7. Inability to pass gas or have a bowel movement
8. Pain that worsens when walking, coughing, or taking deep breaths

**Possible Causes:**
The exact cause of appendicitis is not always clear, but it's believed to be due to an obstruction in the appendix, most commonly by fecal matter. Other possible causes include:

1. Infection from bacteria such as E. coli or Streptococcus
2. Enlarged lymph nodes
3. Tumors or cysts
4. Foreign objects
5. Inflammatory bowel disease

**Diagnosis:**
To diagnose appendicitis, a healthcare professional will consider the patient's symptoms and medical history, perform a physical examination, and may order imaging tests such as ultrasound or CT scan to confirm the diagnosis.

**Treatment:**
Appendicitis cannot be cured with medicine alone. The standard treatment for appendicitis is surgical removal of the appendix, known as an appendectomy. This procedure can be performed using traditional open surgery or laparoscopically.

**Complications:**
If left untreated, appendicitis can lead to serious complications such as:

1. Perforation and rupture of the appendix, which can cause peritonitis (a potentially life-threatening infection)
2. Abscess formation
3. Fistula development
4. Bowel obstruction
5. Sepsis

**Precautions:**
To prevent appendicitis, maintain a balanced diet, stay hydrated, and practice good hygiene. If you experience symptoms suggestive of appendicitis, seek medical attention prompt

`Query 3: What are the effective treatments or solutions for addressing sudden patchy hair loss, commonly seen as localized bald spots on the scalp, and what could be the possible causes behind it?(With all 5 combinations)`

In [ ]:
for config in prompt_configurations:

    print("=" * 100)
    print(config["name"])
    print("=" * 100)

    answer = generate_prompt_response(
        question=query_3.replace("[INST]", "").replace("[/INST]", ""),
        system_instruction=config["instruction"],
        max_tokens=config["max_tokens"],
        temperature=config["temperature"],
        top_p=config["top_p"],
        top_k=config["top_k"]
    )

    print(answer)

====================================================================================================
Configuration 1 - Basic
====================================================================================================

Llama.generate: prefix-match hit

Sudden patchy hair loss, also known as alopecia areata, is an autoimmune condition that causes hair loss in small patches on the scalp. The exact cause of alopecia areata is unknown, but it's believed to be related to an issue with the immune system attacking hair follicles.

Effective treatments for addressing sudden patchy hair loss include:

1. Corticosteroids: These medications can help reduce inflammation and suppress the immune response that causes hair loss. They can be applied topically or taken orally.
2. Immunotherapy: This involves using substances that stimulate an immune response to promote hair regrowth. One common immunotherapy treatment is called diphenylcyclopropenone (DPCP).
3. Minoxidil: This medication can help slow down hair loss and promote new hair growth. It's applied topically.
4. Nutritional supplements: Certain vitamins and minerals, such as biotin and zinc, may help support healthy hair growth.
5. Stress management: Managing stress through techniques like meditation, yoga, or therapy can help reduce the impact of stress on hair loss.

It's important to note that while these treatments can be effective, they don't work for everyone and results can vary. In some cases, hair may grow back on its own without any treatment
====================================================================================================
Configuration 2 - Structured
====================================================================================================

Llama.generate: prefix-match hit

1. Key symptoms/findings: Sudden patchy hair loss is characterized by the appearance of localized bald spots on the scalp. The hair in these areas may come out easily when pulled or brushed, leaving small, round patches of exposed skin.
2. Possible causes or diagnosis: There are several possible causes for sudden patchy hair loss, including:
   a. Alopecia Areata: An autoimmune condition that causes hair loss in circular patches on the scalp, beard, or other areas of the body.
   b. Telogen Effluvium: A type of hair loss where large numbers of hairs enter the resting phase (telogen) and fall out prematurely. This can be caused by stress, illness, or certain medications.
   c. Traction Alopecia: Hair loss due to excessive pulling or tension on the hair, often seen in people who wear tight braids or ponytails.
   d. Nutritional deficiencies: Lack of essential nutrients such as iron, zinc, or biotin can lead to hair loss.
3. Treatment/management: The treatment for sudden patchy hair loss depends on the underlying cause. For autoimmune conditions like alopecia areata, topical or systemic corticosteroids, immunomodulators, or phototherapy may be prescribed. In cases of telogen effluvium, addressing the underlying cause (e.g., stress reduction, nutritional supplements) and practicing good hair care can help promote regrowth. For traction alopecia, avoiding tight hairstyles
====================================================================================================
Configuration 3 - Clinical
====================================================================================================

Llama.generate: prefix-match hit

I. Introduction
Sudden patchy hair loss, also known as alopecia areata, is a common autoimmune disorder that results in the sudden appearance of smooth, round, or patchy bald spots on the scalp. This condition can affect people of all ages and genders. In this response, we will discuss the possible causes, symptoms, diagnosis, treatments, and complications of alopecia areata.

II. Causes
The exact cause of alopecia areata is unknown, but it's believed to be an autoimmune disorder where the body's immune system attacks hair follicles, leading to hair loss. Some possible triggers include stress, illness, hormonal imbalances, and certain medications.

III. Symptoms
The primary symptom of alopecia areata is the sudden appearance of smooth, round, or patchy bald spots on the scalp. However, it can also affect other areas of the body such as the beard, eyebrows, or eyelashes. In some cases, complete hair loss (alopecia totalis) or total body hair loss (alopecia universalis) may occur.

IV. Diagnosis
Alopecia areata is typically diagnosed based on its appearance and medical history. A dermatologist may perform a scalp biopsy to rule out other conditions, but it's not always necessary.

V. Treatments
There is no cure for alopecia areata, but various treatments can help promote hair regrowth or slow down the progression of hair loss:
1. Topical corticosteroids: These anti-inflammatory medications can be applied directly to the bald spots to reduce inflammation and promote hair growth.
2. Injections: Corticosteroid injections into the bald spots may be more effective than topical treatments
====================================================================================================
Configuration 4 - Conservative
====================================================================================================

Llama.generate: prefix-match hit

I. Possible Causes of Sudden Patchy Hair Loss (Alopecia Areata):
1. Autoimmune disorder: The immune system mistakenly attacks hair follicles, causing hair loss.
2. Stress: Emotional or physical stress can trigger the onset of alopecia areata.
3. Genetics: There is a higher risk of developing alopecia areata if there is a family history of the condition.
4. Viral infections: Certain viruses may contribute to hair loss.
5. Other health conditions: Thyroid disease, lupus, or other autoimmune disorders can cause patchy hair loss.
6. Medications: Some drugs, such as certain antidepressants and chemotherapy medications, can lead to hair loss.
7. Trauma: Physical trauma to the scalp, such as burns or injury, may result in patchy hair loss.

II. Effective Treatments for Patchy Hair Loss (Alopecia Areata):
1. Topical treatments: Corticosteroids applied directly to the affected area can help stimulate hair growth. Minoxidil is another topical treatment that has been shown to be effective in some cases.
2. Injections: Intralesional corticosteroid injections may be used for more severe cases of alopecia areata.
3. Systemic treatments: Oral corticosteroids, immunosuppressive drugs, or other systemic medications may be prescribed for extensive hair loss or when topical treatments are not effective.
4. Light therapy: Exposure to ultraviolet A (UVA) or broadband UVB light can help stimulate hair growth in some cases of alopecia areata.
5. Alternative therapies: Acupuncture, herbal remed
====================================================================================================
Configuration 5 - Detailed
====================================================================================================

Llama.generate: prefix-match hit

Title: Sudden Patchy Hair Loss: Causes, Diagnosis, Treatment, Complications, and Precautions

1. Symptoms:
Sudden patchy hair loss, also known as alopecia areata, is characterized by round or oval bald spots on the scalp that may appear suddenly. The affected areas typically have normal-looking skin with fine hairs or no visible hairs at all. In some cases, there might be itching or burning sensations before the hair falls out.

2. Possible Causes:
Alopecia areata is an autoimmune disorder where the body's immune system attacks hair follicles, leading to hair loss. Other possible causes include stress, genetics, vitamin deficiencies (especially iron or biotin), hormonal imbalances, and certain medications. Infections such as ringworm can also cause patchy hair loss.

3. Diagnosis:
A healthcare professional will typically diagnose alopecia areata based on the appearance of the bald spots and a thorough medical history. They may perform blood tests to rule out other conditions that could be causing hair loss. A skin biopsy might be necessary in some cases.

4. Treatment:
There is no definitive cure for alopecia areata, but various treatments can help stimulate hair regrowth or slow down the progression of hair loss. These include:
   a. Topical corticosteroids: These anti-inflammatory medications can be applied directly to the bald spots to reduce inflammation and promote hair growth.
   b. Immunomodulatory agents: Drugs like minoxidil or anthralin can help regrow lost hair by suppressing the immune system's attack on hair follicles.
   c. Injections: Intralesional corticosteroid injections can be administered every 4-6 weeks to stimulate hair growth.
   d. Light therapy: Low-level laser therapy or phototherapy may help promote hair regrowth by increasing blood flow and nutrient supply to the affected areas.

5. Complications:
Complications of alopecia areata include psychological distress due to the cosmetic appearance of bald spots, as well as potential progression to total hair loss (

**Query 4: What treatments are recommended for a person who has sustained a physical injury to brain tissue, resulting in temporary or permanent impairment of brain function?(With all 5 combinations)**

In [ ]:
for config in prompt_configurations:

    print("=" * 100)
    print(config["name"])
    print("=" * 100)

    answer = generate_prompt_response(
        question=query_4.replace("[INST]", "").replace("[/INST]", ""),
        system_instruction=config["instruction"],
        max_tokens=config["max_tokens"],
        temperature=config["temperature"],
        top_p=config["top_p"],
        top_k=config["top_k"]
    )

    print(answer)

====================================================================================================
Configuration 1 - Basic
====================================================================================================

Llama.generate: prefix-match hit

Treatment for a brain injury depends on the severity and location of the injury. Here are some common treatments:

1. Medical Management: This includes controlling any bleeding, managing seizures, and addressing any life-threatening conditions.
2. Rehabilitation: Physical therapy, occupational therapy, speech therapy, and cognitive rehabilitation can help improve function and reduce symptoms.
3. Medications: Various medications may be prescribed to manage symptoms such as pain, swelling, seizures, or depression.
4. Surgery: In some cases, surgery may be necessary to remove hematomas (clots) or repair skull fractures.
5. Assistive Devices: Devices like wheelchairs, walkers, or communication aids can help individuals with brain injuries function better in their daily lives.
6. Lifestyle Modifications: Making lifestyle changes such as getting enough rest, eating well, and avoiding alcohol and drugs can promote healing and improve overall health.
7. Support Groups: Joining support groups can provide emotional and social support for individuals with brain injuries and their families.
8. Vocational Counseling: In some cases, vocational counseling may be necessary to help individuals return to work or find new employment opportunities.

It's important to note that treatment for a brain injury is often complex and may involve a team of healthcare professionals. If you or someone you know has
====================================================================================================
Configuration 2 - Structured
====================================================================================================

Llama.generate: prefix-match hit

1. Key symptoms/findings: A person with a brain injury may experience various symptoms such as headache, dizziness, loss of consciousness, memory problems, difficulty speaking or understanding speech, and changes in mood or behavior. Seizures, paralysis, and coma are also possible depending on the severity of the injury.
2. Possible causes or diagnosis: A brain injury can be caused by various factors including trauma (e.g., car accidents, falls), infections (e.g., meningitis, encephalitis), tumors, or stroke. Brain injuries are typically diagnosed through a combination of physical examination, imaging studies (such as CT or MRI scans), and neurological assessments.
3. Treatment/management: The treatment for a brain injury depends on the severity and cause of the injury. For mild to moderate brain injuries, rest, rehabilitation, and medication to manage symptoms may be sufficient. Severe brain injuries may require surgery, intensive care unit (ICU) admission, and long-term rehabilitation. Rehabilitation may include physical therapy, occupational therapy, speech therapy, and cognitive rehabilitation.
4. Important precautions: It is important to seek medical attention promptly for a suspected brain injury. Delaying treatment can worsen the outcome. Additionally, individuals with brain injuries should avoid activities that could cause further harm, such as contact sports or heavy lifting, until they have fully recovered. They may also require modifications to their home and work environment to accommodate any permanent impairments.
====================================================================================================
Configuration 3 - Clinical
====================================================================================================

Llama.generate: prefix-match hit

I. Introduction
- Brain injuries can result in various degrees of impairment to brain function, ranging from mild concussions to severe traumatic brain injuries (TBI).
- Treatment for brain injuries depends on the severity and specific symptoms present.

II. Symptoms
- Common symptoms of brain injuries include: headache, dizziness, memory loss, difficulty speaking or understanding speech, weakness or paralysis, and changes in mood or behavior.

III. Diagnosis
- Brain injuries are typically diagnosed through a combination of medical history, physical examination, imaging studies (such as CT or MRI scans), and neurological assessments.

IV. Treatment
1. Acute Care:
   - In the acute phase, treatment may include: managing increased intracranial pressure, preventing infection, controlling seizures, and providing supportive care to maintain vital functions.

2. Rehabilitation:
   - Rehabilitation is an essential component of treatment for brain injuries. It may involve physical therapy, occupational therapy, speech therapy, cognitive rehabilitation, and behavioral management.
   - The goal of rehabilitation is to help the individual regain as much function as possible and learn strategies to manage any remaining impairments.

3. Medications:
   - Depending on the specific symptoms present, various medications may be prescribed to manage conditions such as seizures, pain, or depression.

4. Surgery:
   - In some cases, surgery may be necessary to remove hematomas (clots of blood) or repair skull fractures.

V. Complications
- Complications of brain injuries can include: infections, seizures, hemorrhages, hydrocephalus (an accumulation of cerebrospinal fluid), and cognitive impairments.
- Close monitoring and
====================================================================================================
Configuration 4 - Conservative
====================================================================================================

Llama.generate: prefix-match hit

Based on current medical knowledge, the treatment for a person with a brain injury depends on the severity and specific location of the injury. Here are some common interventions:

1. Initial Management: This includes addressing any life-threatening conditions such as airway obstruction, breathing difficulties, or excessive bleeding. In some cases, surgery may be required to remove hematomas (clots) or repair skull fractures.

2. Supportive Care: Patients with brain injuries often require close monitoring in an intensive care unit. They may need assistance with breathing, feeding, and other basic functions. Rehabilitation therapies such as physical therapy, occupational therapy, and speech therapy may also be initiated early to help prevent complications and promote recovery.

3. Medications: Various medications can be used to manage symptoms associated with brain injuries, including pain relievers, anti-seizure drugs, and medications to reduce intracranial pressure.

4. Nutritional Support: Brain injuries can make it difficult for patients to eat or drink properly. Enteral nutrition (feeding through a tube) may be necessary to ensure adequate caloric intake and prevent malnutrition.

5. Rehabilitation: The goal of rehabilitation is to help patients regain lost function and improve their quality of life. This can include physical therapy to address motor deficits, occupational therapy to help with daily living skills, speech therapy for communication issues, and cognitive rehabilitation to address memory and attention problems.

6. Psychological Support: Brain injuries can have significant emotional and psychological effects on patients and their families. Counseling and support groups can be helpful in managing these challenges.

7. Prevention of Secondary Injury: Brain injuries can lead to further damage if not properly managed. This includes preventing complications such as infection, blood clots, and pressure build-
====================================================================================================
Configuration 5 - Detailed
====================================================================================================

Llama.generate: prefix-match hit

Title: Brain Injury: Symptoms, Causes, Diagnosis, Treatment, Complications, Precautions, and Emergency Considerations

1. Symptoms of Brain Injury:
- Headache or a feeling of pressure in the head.
- Temporary loss of consciousness or disorientation.
- Confusion or memory problems.
- Dizziness or loss of balance.
- Nausea or vomiting.
- Slurred speech.
- Changes in mood, behavior, or personality.
- Seizures.
- Paralysis or weakness in limbs.
- Sensory impairments such as vision or hearing changes.

2. Possible Causes of Brain Injury:
- Trauma (car accidents, falls, sports injuries).
- Penetrating wounds from bullets or other objects.
- Birth injury.
- Toxic substances (lead, mercury, carbon monoxide).
- Infections (meningitis, encephalitis).
- Stroke or transient ischemic attack (TIA).
- Brain tumors.

3. Diagnosis of Brain Injury:
- Physical examination.
- Neurological exam.
- Imaging tests such as CT scan or MRI.
- Blood tests to rule out infections or toxic substances.
- Cerebrospinal fluid analysis.

4. Treatment for Brain Injury:
- Rest and recovery.
- Medications to manage symptoms (pain relievers, anti-seizure drugs).
- Surgery if there is a penetrating wound or hematoma.
- Rehabilitation therapies such as physical therapy, occupational therapy, speech therapy, and cognitive rehabilitation.
- Assistive devices like wheelchairs, braces, or communication aids.

5. Complications of Brain Injury:
- Chronic pain.
- Epilepsy.
- Cognitive impairments such as memory loss, attention deficits, and problem-solving difficulties.
- Emotional and behavioral changes.
- Paralysis or muscle weakness.
- Speech and language problems.
- Hydrocephalus

**Query 5: What are the necessary precautions and treatment steps for a person who has fractured their leg during a hiking trip, and what should be considered for their care and recovery?(With all 5 combinations)**

In [ ]:
for config in prompt_configurations:

    print("=" * 100)
    print(config["name"])
    print("=" * 100)

    answer = generate_prompt_response(
        question=query_5.replace("[INST]", "").replace("[/INST]", ""),
        system_instruction=config["instruction"],
        max_tokens=config["max_tokens"],
        temperature=config["temperature"],
        top_p=config["top_p"],
        top_k=config["top_k"]
    )

    print(answer)

====================================================================================================
Configuration 1 - Basic
====================================================================================================

Llama.generate: prefix-match hit

A fractured leg, also known as a broken leg, requires immediate medical attention. Here are the necessary precautions and treatment steps:

1. Immediate Care: If you suspect a fracture, do not move the person unless it is necessary to prevent harm. Apply a makeshift splint if possible, using materials like sticks, clothes, or backpacking poles. Do not attempt to realign the bone.

2. Transportation: Call for emergency medical help and provide them with your location. If transporting the person yourself, try to keep them as comfortable as possible during the journey. Keep in mind that bumps and jolts can cause additional pain and discomfort.

3. Hospital Treatment: In the hospital, doctors will assess the fracture and determine the best course of treatment. This may include setting the bone with pins or a cast, administering pain medication, and monitoring for complications like infection or blood clots.

4. Recovery: The recovery process can take several weeks to months depending on the severity of the fracture. During this time, follow your healthcare provider's instructions carefully. This may include using crutches or a wheelchair, attending physical therapy sessions, and taking prescribed medications as needed.

5. Considerations for Care: Proper care during recovery includes maintaining good hygiene around the injury site, eating a balanced diet to support healing, getting plenty of
====================================================================================================
Configuration 2 - Structured
====================================================================================================

Llama.generate: prefix-match hit

1. Key symptoms/findings: A person with a fractured leg may experience severe pain, swelling, bruising, deformity, or inability to bear weight on the affected limb. In some cases, there may be visible bone protrusion through the skin (open fracture), which requires immediate medical attention.

2. Possible causes or diagnosis: A leg fracture can occur due to various reasons such as falling, twisting, or direct trauma. The diagnosis is typically made based on a physical examination and imaging studies like X-rays.

3. Treatment/management: The initial step in managing a leg fracture is immobilization using a cast, splint, or traction to prevent movement and promote healing. Pain management through medications, ice packs, or elevation may also be necessary. In severe cases, surgery might be required to realign the bone and stabilize it with plates, screws, or rods. Rehabilitation including physical therapy and exercises will help restore strength and mobility.

4. Important precautions: It is essential to avoid putting weight on the affected leg until it has healed completely. Proper wound care is crucial for open fractures. Regular follow-up appointments with a healthcare professional are necessary to monitor progress, adjust treatment plans if needed, and ensure a full recovery. Additionally, individuals should be cautious about infection signs such as redness, warmth, or increased pain, which may indicate an infection that requires prompt medical attention.
====================================================================================================
Configuration 3 - Clinical
====================================================================================================

Llama.generate: prefix-match hit

A leg fracture, also known as a broken leg, is a common injury that can occur during physical activities like hiking. Here's a clinically organized answer to your question:

Symptoms:
- Severe pain in the affected leg
- Swelling and bruising around the injured area
- Difficulty walking or putting weight on the leg
- Deformity or misalignment of the bone, if it is a severe fracture
- Numbness or tingling sensations below the injury site

Diagnosis:
A healthcare professional will diagnose a leg fracture based on a physical examination and medical imaging tests such as X-rays.

Treatment:
1. Immediate first aid: Apply a splint or immobilize the leg with a makeshift sling to prevent further damage and provide support.
2. Seek medical attention: It's essential to seek professional medical care as soon as possible for proper diagnosis, treatment, and follow-up care.
3. Medical intervention: Depending on the severity of the fracture, treatments may include casting, surgery, or the use of a bone stimulator.
4. Pain management: Your healthcare provider may prescribe pain medication to help manage discomfort during the healing process.
5. Rest and immobilization: Avoid putting weight on the injured leg and follow your doctor's instructions regarding crutches or other assistive devices.
6. Rehabilitation: Physical therapy exercises will be recommended to restore strength, flexibility, and mobility to the affected leg.

Complications:
1. Infection: Monitor for signs of infection such as redness, warmth, swelling, or pus at the injury site.
2. Blood clots: The risk of developing blood clots in the injured leg is higher due to immobility. Your healthcare provider may prescribe blood
====================================================================================================
Configuration 4 - Conservative
====================================================================================================

Llama.generate: prefix-match hit

A leg fracture sustained during a hiking trip requires prompt medical attention to ensure proper healing and prevent potential complications. Here are the necessary precautions and treatment steps:

1. Assess the severity of the injury: Determine if it is an open or closed fracture, and assess for any signs of nerve or blood vessel damage, such as numbness, tingling, or pulselessness. If there are any signs of severe bleeding or shock, call emergency services immediately.
2. Immobilize the leg: Use a splint, sling, or a makeshift device to prevent further movement and potential worsening of the fracture. Be careful not to apply too much pressure on the injury site.
3. Provide pain relief: Over-the-counter pain medications like acetaminophen or ibuprofen can help manage pain. If the pain is severe, prescription pain medication may be necessary.
4. Seek medical attention: It's essential to see a healthcare professional as soon as possible for proper diagnosis and treatment. X-rays will be needed to confirm the fracture location and extent.
5. Follow the doctor's instructions: Depending on the severity of the fracture, treatment may include casting, surgery, or other interventions. Adhere strictly to the prescribed care plan, including any physical therapy exercises or restrictions on weight-bearing activities.
6. Monitor for complications: Keep an eye out for signs of infection, such as redness, swelling, or increased pain, and report them to your healthcare provider immediately. Additionally, be aware of potential complications like blood clots, which may require preventative measures like compression stockings or medication.
7. Allow for adequate healing time: Full recovery from a leg fracture can take several weeks to months, depending on the severity of the injury and the individual's overall health
====================================================================================================
Configuration 5 - Detailed
====================================================================================================

Llama.generate: prefix-match hit

Title: Fractured Leg: Necessary Precautions, Treatment, and Recovery Considerations

1. Symptoms:
- Intense pain in the affected leg
- Swelling, bruising, or deformity around the fracture site
- Difficulty moving the leg or walking
- Inability to bear weight on the leg
- Possible numbness or tingling sensations

2. Possible Causes:
A fractured leg can occur due to various reasons such as falling, tripping, or twisting the leg in an unusual way while hiking.

3. Diagnosis:
The diagnosis of a fractured leg involves a thorough physical examination and medical history assessment. Imaging tests like X-rays are typically used to confirm the diagnosis and determine the severity and location of the fracture.

4. Treatment:
- RICE (Rest, Ice, Compression, Elevation): Rest the leg as much as possible, apply ice packs to reduce swelling, use a compression bandage or brace, and keep the leg elevated above heart level.
- Immobilization: A cast, splint, or brace may be used to immobilize the fractured leg and promote proper healing.
- Pain management: Over-the-counter pain medications like acetaminophen or prescription painkillers may be recommended to help manage the pain.
- Surgery: In some cases, surgery might be necessary to realign the bone fragments or insert metal plates or screws for stabilization.

5. Complications:
Complications of a fractured leg can include infection, delayed healing, blood clots (deep vein thrombosis), nerve damage, and chronic pain. Regular follow-up appointments with your healthcare provider are essential to monitor progress and address any potential complications.

6. Precautions:
- Avoid putting weight on the affected leg until it has healed completely.
- Keep the cast or brace dry to prevent infection.
- Follow a doctor-recommended exercise routine to maintain flexibility and strength in the affected leg during recovery.
- Be cautious when returning to hiking activities to avoid reinjuring the leg.

7. Emergency Considerations:
If you suspect that someone has fractured their leg while hiking, follow these

**Observation:**


The five configurations illustrate different levels of depth and clinical framing:

Basic gives a quick overview of the condition and highlights common treatments.

Structured organizes symptoms, causes, and management clearly, while also noting alternative causes.

Clinical provides a guideline‑style explanation, including diagnosis methods and treatment options.

Conservative emphasizes a cautious approach, listing multiple possible causes (autoimmune, stress, genetics, medications) and a range of treatments from topical to systemic.

Detailed offers the most comprehensive coverage, including symptoms, causes, diagnosis, treatment options, complications, and precautions.

**Overall insight:** Shorter outputs are useful for rapid recognition and quick decision‑support, while structured and detailed versions provide richer context for clinical validation, teaching, and patient communication.

##Data Preparation for RAG

###**Loading the Data**

In [ ]:
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain_community.document_loaders import PyMuPDFLoader
from langchain_community.embeddings.sentence_transformer import SentenceTransformerEmbeddings
from langchain_community.vectorstores import Chroma

In [ ]:
pdf_path = "/content/medical_diagnosis_manual.pdf"

loader = PyMuPDFLoader(pdf_path)

pages = loader.load()

print("Number of pages loaded:", len(pages))

Number of pages loaded: 4114

###Data Overview

**Checking the first 5 pages**

In [ ]:
for i in range(min(5, len(pages))):

    print("=" * 100)
    print(f"PAGE {i + 1}")
    print("=" * 100)

    print(pages[i].page_content[:1500])

====================================================================================================
PAGE 1
====================================================================================================
shahanam04@gmail.com
UPWIKCV2H5
This file is meant for personal use by shahanam04@gmail.com only.
Sharing or publishing the contents in part or full is liable for legal action.
====================================================================================================
PAGE 2
====================================================================================================
shahanam04@gmail.com
UPWIKCV2H5
This file is meant for personal use by shahanam04@gmail.com only.
Sharing or publishing the contents in part or full is liable for legal action.
====================================================================================================
PAGE 3
====================================================================================================
Table of Contents
1
Front    ................................................................................................................................................................................................................
1
Cover    .......................................................................................................................................................................................................
2
Front Matter    ...........................................................................................................................................................................................
53
1 - Nutritional Disorders    ...............................................................................................................................................................
53
Chapter 1. Nutrition: General Considerations    .....................................................................................................................
59
Chapter 2. Undernutrition    .............................................................................................................................................................
69
Chapter 3. Nutritional Support    ...................................................................................................................................................
76
Chapter 4. Vitamin Deficiency, Dependency & Toxicity    ..................................................
====================================================================================================
PAGE 4
====================================================================================================
491
Chapter 44. Foot & Ankle Disorders    .....................................................................................................................................
502
Chapter 45. Tumors of Bones & Joints    ...............................................................................................................................
510
5 - Ear, Nose, Throat & Dental Disorders    ..................................................................................................................
510
Chapter 46. Approach to the Patient With Ear Problems    ...........................................................................................
523
Chapter 47. Hearing Loss    .........................................................................................................................................................
535
Chapter 48. Inner Ear Disorders    ............................................................................................................................................
542
Chapter 49. Middle Ear & Tympanic Membrane Disorders    ........................................................................................
550
Chapter 50. External Ear Disorders    .....................................................................................................................................
554
Chapter 51. Approach to the Patient With Nasal & Pharyngeal Symptoms    .......................................................
567
Chapter 5
====================================================================================================
PAGE 5
====================================================================================================
921
Chapter 94. Adrenal Disorders    ................................................................................................................................................
936
Chapter 95. Polyglandular Deficiency Syndromes    ........................................................................................................
939
Chapter 96. Porphyrias    ..............................................................................................................................................................
949
Chapter 97. Fluid & Electrolyte Metabolism    .....................................................................................................................
987
Chapter 98. Acid-Base Regulation & Disorders    ..............................................................................................................
1001
Chapter 99. Diabetes Mellitus & Disorders of Carbohydrate Metabolism    ........................................................
1024
Chapter 100. Lipid Disorders    ................................................................................................................................................
1034
Chapter 101. Amyloidosis    ......................................................................................................................................................
1037
Chapter 102. Carcinoid Tumors    .....................................................................................................

**Observation:**

 The PDF contains extensive medical information organized across multiple sections. Page-level metadata is retained so that retrieved information can later be traced back to the source document.

###**Checking the number of pages**

In [ ]:
print("Total number of pages:", len(pages))

Total number of pages: 4114

In [ ]:
print("Metadata of first page:")
print(pages[0].metadata)

Metadata of first page:
{'producer': 'pdf-lib (https://github.com/Hopding/pdf-lib)', 'creator': 'Atop CHM to PDF Converter', 'creationdate': '2012-06-15T05:44:40+00:00', 'source': '/content/medical_diagnosis_manual.pdf', 'file_path': '/content/medical_diagnosis_manual.pdf', 'total_pages': 4114, 'format': 'PDF 1.7', 'title': 'The Merck Manual of Diagnosis & Therapy, 19th Edition', 'author': '', 'subject': '', 'keywords': '', 'moddate': '2026-08-11T04:47:29+00:00', 'trapped': '', 'modDate': 'D:20260811044729Z', 'creationDate': 'D:20120615054440Z', 'page': 0}

###Data Chunking

In [ ]:
text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=1500,
    chunk_overlap=200,
    separators=["\n\n", "\n", ". ", " ", ""]
)

chunks = text_splitter.split_documents(pages)

print("Number of chunks:", len(chunks))

Number of chunks: 11972

Check

In [ ]:
print("First chunk:")
print(chunks[0].page_content[:1500])

print("\nMetadata:")
print(chunks[0].metadata)

First chunk:
shahanam04@gmail.com
UPWIKCV2H5
This file is meant for personal use by shahanam04@gmail.com only.
Sharing or publishing the contents in part or full is liable for legal action.

Metadata:
{'producer': 'pdf-lib (https://github.com/Hopding/pdf-lib)', 'creator': 'Atop CHM to PDF Converter', 'creationdate': '2012-06-15T05:44:40+00:00', 'source': '/content/medical_diagnosis_manual.pdf', 'file_path': '/content/medical_diagnosis_manual.pdf', 'total_pages': 4114, 'format': 'PDF 1.7', 'title': 'The Merck Manual of Diagnosis & Therapy, 19th Edition', 'author': '', 'subject': '', 'keywords': '', 'moddate': '2026-08-11T04:47:29+00:00', 'trapped': '', 'modDate': 'D:20260811044729Z', 'creationDate': 'D:20120615054440Z', 'page': 0}

**Observation:**

 The document is divided into overlapping chunks so that individual retrieved passages contain sufficient context while avoiding the need to pass the entire 4,000+ page manual to the LLM. A chunk overlap of 200 characters helps preserve contextual continuity between neighboring chunks.

###**Embedding**

In [ ]:
from langchain_community.embeddings.sentence_transformer import SentenceTransformerEmbeddings

embedding_model = SentenceTransformerEmbeddings(
    model_name="all-MiniLM-L6-v2"
)

print("Embedding model loaded successfully.")

/tmp/ipykernel_13388/3542779328.py:3: LangChainDeprecationWarning: The class `HuggingFaceEmbeddings` was deprecated in LangChain 0.2.2 and will be removed in 1.0. An updated version of the class exists in the :class:`~langchain-huggingface package and should be used instead. To use it run `pip install -U :class:`~langchain-huggingface` and import as `from :class:`~langchain_huggingface import HuggingFaceEmbeddings``.
  embedding_model = SentenceTransformerEmbeddings(

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Embedding model loaded successfully.

**Observation:**

Sentence Transformer embeddings convert the text chunks into numerical vectors representing their semantic meaning. This allows the retriever to identify passages that are semantically related to the user's question rather than relying only on exact keyword matching.

###**Vector Database**

In [ ]:
from langchain_community.vectorstores import Chroma

vector_db = Chroma.from_documents(
    documents=chunks,
    embedding=embedding_model,
    collection_name="merck_medical_manual"
)

print("Vector database created successfully.")

ERROR:chromadb.telemetry.product.posthog:Failed to send telemetry event ClientStartEvent: capture() takes 1 positional argument but 3 were given
ERROR:chromadb.telemetry.product.posthog:Failed to send telemetry event ClientCreateCollectionEvent: capture() takes 1 positional argument but 3 were given

Vector database created successfully.

**Observation:**

The medical document chunks and their embeddings are stored in a Chroma vector database. This provides the retrieval layer required by the RAG architecture.

###**Retriever**

In [ ]:
retriever = vector_db.as_retriever(
    search_type="similarity",
    search_kwargs={"k": 3}
)

print("Retriever configured successfully.")
print("Search type: similarity")
print("k:", 3)

Retriever configured successfully.
Search type: similarity
k: 3

In [ ]:
test_query = "What are the symptoms and treatment of sepsis?"

retrieved_docs = retriever.invoke(test_query)

print("Retrieved documents:", len(retrieved_docs))

for i, doc in enumerate(retrieved_docs, 1):

    print("=" * 100)
    print(f"Retrieved Chunk {i}")
    print("Metadata:", doc.metadata)
    print(doc.page_content[:1000])

ERROR:chromadb.telemetry.product.posthog:Failed to send telemetry event CollectionQueryEvent: capture() takes 1 positional argument but 3 were given

Retrieved documents: 3
====================================================================================================
Retrieved Chunk 1
Metadata: {'author': '', 'creationDate': 'D:20120615054440Z', 'creationdate': '2012-06-15T05:44:40+00:00', 'creator': 'Atop CHM to PDF Converter', 'file_path': '/content/medical_diagnosis_manual.pdf', 'format': 'PDF 1.7', 'keywords': '', 'modDate': 'D:20260811044729Z', 'moddate': '2026-08-11T04:47:29+00:00', 'page': 2454, 'producer': 'pdf-lib (https://github.com/Hopding/pdf-lib)', 'source': '/content/medical_diagnosis_manual.pdf', 'subject': '', 'title': 'The Merck Manual of Diagnosis & Therapy, 19th Edition', 'total_pages': 4114, 'trapped': ''}
factors, excessive fibrinolysis in reaction thereto, and more often a combination of both.
Symptoms and Signs
With sepsis, the patient typically has fever, tachycardia, and tachypnea; BP remains
[Table 227-1. Sepsis in the United States]
normal. Other signs of the causative infection are generally present. As severe sepsis or septic shock
develops, the first sign may be confusion or decreased alertness. BP generally falls, yet the skin is
paradoxically warm. Oliguria (< 0.5 mL/kg/h) is likely to be present. Later, extremities become cool and
pale, with peripheral cyanosis and mottling. Organ failure causes additional symptoms and signs specific
to the organ involved.
Diagnosis
Sepsis is suspected when a patient with a known infection develops systemic signs of inflammation or
organ dysfunction. Similarly, a patient with otherwise unexplained signs of systemic inflammation should
be evaluated for infection by history, physical examination, and tests, including urinalysis and urine cultu
====================================================================================================
Retrieved Chunk 2
Metadata: {'author': '', 'creationDate': 'D:20120615054440Z', 'creationdate': '2012-06-15T05:44:40+00:00', 'creator': 'Atop CHM to PDF Converter', 'file_path': '/content/medical_diagnosis_manual.pdf', 'format': 'PDF 1.7', 'keywords': '', 'modDate': 'D:20260811044729Z', 'moddate': '2026-08-11T04:47:29+00:00', 'page': 2995, 'producer': 'pdf-lib (https://github.com/Hopding/pdf-lib)', 'source': '/content/medical_diagnosis_manual.pdf', 'subject': '', 'title': 'The Merck Manual of Diagnosis & Therapy, 19th Edition', 'total_pages': 4114, 'trapped': ''}
can approximate bone marrow NSP levels. I:T ratios of > 0.80 correlate with NSP depletion and death;
such a ratio may identify neonates who might benefit from granulocyte transfusion.
Treatment
• Antibiotic therapy
• Supportive therapy
Because sepsis may manifest with non-specific clinical signs and its effects may be devastating, rapid
empiric antibiotic therapy is recommended (see p. 1182); drugs are later adjusted according to
sensitivities and the site of infection. If bacterial cultures show no growth by 48 h (although some
pathogens may require 72 h) and the neonate appears well, antibiotics are stopped.
General supportive measures, including respiratory and hemodynamic management, are combined with
antibiotic treatment.
Antimicrobials: In early-onset sepsis, initial therapy should include ampicillin or penicillin G plus an
aminoglycoside. Cefotaxime may be added to or substituted for the aminoglycoside if meningitis is
suspected. If foul-smelling amniotic fluid is present at bir
====================================================================================================
Retrieved Chunk 3
Metadata: {'author': '', 'creationDate': 'D:20120615054440Z', 'creationdate': '2012-06-15T05:44:40+00:00', 'creator': 'Atop CHM to PDF Converter', 'file_path': '/content/medical_diagnosis_manual.pdf', 'format': 'PDF 1.7', 'keywords': '', 'modDate': 'D:20260811044729Z', 'moddate': '2026-08-11T04:47:29+00:00', 'page': 2453, 'producer': 'pdf-lib (https://github.com/Hopding/pdf-lib)', 'source': '/content/medical_diagnosis_manual.pdf', 'subject': '', 'title': 'The Merck Manual of Diagnosis & Therapy, 19th Edition', 'total_pages': 4114, 'trapped': ''}
Chapter 227. Sepsis and Septic Shock
Introduction
(See also Ch. 226.)
Sepsis, severe sepsis, and septic shock are inflammatory states resulting from the systemic
response to bacterial infection. In severe sepsis and septic shock, there is critical reduction in
tissue perfusion. Common causes include gram-negative organisms, staphylococci, and
meningococci. Symptoms often begin with shaking chills and include fever, hypotension,
oliguria, and confusion. Acute failure of multiple organs, including the lungs, kidneys, and liver,
can occur. Treatment is aggressive fluid resuscitation, antibiotics, surgical excision of infected
or necrotic tissues and drainage of pus, supportive care, and sometimes intensive control of
blood glucose and administration of corticosteroids and activated protein C.
A spectrum of severity exists (see
Table 227-1).
Sepsis is infection accompanied by an acute inflammatory reaction with systemic manifestations
associated with release into the bloodstream of numerou

**Observation:**

 Similarity-based retrieval with k=3 returns the three document chunks that are most semantically similar to the query. This provides the LLM with focused medical context instead of the complete manual.

###**System and User Prompt Template**

In [ ]:
qna_system_message = """
You are a medical information assistant supporting healthcare professionals.

Use ONLY the information contained in the provided context from the Merck Manuals
to answer the question.

Do not invent facts or introduce unsupported medical information.

If the provided context does not contain enough information to answer the question,
clearly state that the available context is insufficient.

Present the response in a clear and clinically organized manner.

Include:
- Key symptoms/findings
- Possible causes or diagnosis
- Treatment/management
- Important precautions
- Relevant source information

This system is intended for medical information support and does not replace
professional clinical judgment.
"""

qna_user_message_template = """
Context from the Merck Manuals:

{context}

Question:

{question}

Answer the question using only the provided context.
"""

**Response Function**

In [ ]:
def generate_rag_response(
    user_input,
    k=3,
    max_tokens=300,
    temperature=0,
    top_p=0.95,
    top_k=50
):

    # Retrieve relevant document chunks
    relevant_document_chunks = retriever.invoke(
        user_input
    )[:k]

    context_list = [
        d.page_content
        for d in relevant_document_chunks
    ]

    # Combine retrieved chunks
    context_for_query = "\n\n".join(context_list)

    user_message = qna_user_message_template.replace(
        "{context}",
        context_for_query
    )

    user_message = user_message.replace(
        "{question}",
        user_input
    )

    prompt = f"""[INST]
{qna_system_message}

{user_message}
[/INST]"""

    try:

        model_output = llm(
            prompt=prompt,
            max_tokens=max_tokens,
            temperature=temperature,
            top_p=top_p,
            top_k=top_k
        )

        generated_response = model_output[
            "choices"
        ][0]["text"].strip()

    except Exception as e:

        generated_response = (
            f"Sorry, I encountered the following error:\n{e}"
        )

    return generated_response, relevant_document_chunks

##**Question Answering using RAG**

`Query 1: What is the protocol for managing sepsis in a critical care unit?`

In [ ]:
answer, retrieved_docs = generate_rag_response(
    query_1.replace("[INST]", "").replace("[/INST]", ""),
    k=3,
    max_tokens=350,
    temperature=0,
    top_p=0.95,
    top_k=50
)

print("RAG ANSWER:")
print(answer)

print("\nRETRIEVED SOURCES:")

for i, doc in enumerate(retrieved_docs, 1):

    print(
        f"\nSource {i} | "
        f"Page: {doc.metadata.get('page', 'N/A')}"
    )

    print(doc.page_content[:500])

Llama.generate: prefix-match hit

RAG ANSWER:
The protocol for managing sepsis in a critical care unit includes the following steps:

1. Fluid resuscitation with 0.9% normal saline until central venous pressure (CVP) reaches 8 mm Hg (10 cm H2O) or pulmonary artery occlusive pressure (PAOP) reaches 12 to 15 mm Hg. Oliguria with hypotension is not a contraindication to vigorous fluid resuscitation.
2. Administration of oxygen.
3. Broad-spectrum antibiotics, modified by culture results.
4. Drainage of abscesses and excision of necrotic tissue.
5. Normalization of blood glucose levels.
6. Replacement-dose corticosteroids (24 μg/kg/h by continuous IV infusion for 96 hours). However, contraindications include hemorrhagic stroke within 3 months, spinal or intracranial surgery within 2 months, acute trauma with a risk of bleeding, and intracranial neoplasm.
7. Monitoring: systemic pressure, CVP or PAOP, pulse oximetry, arterial blood gases (ABGs), blood glucose, lactate, and electrolyte levels, renal function, sublingual PCO2, urine output, and possibly central venous oxygen saturation.
8. Other emerging therapies for severe sepsis include cooling for hyperthermia and early treatment of renal failure with continuous venovenous hemofiltr

RETRIEVED SOURCES:

Source 1 | Page: 2400
16 - Critical Care Medicine
Chapter 222. Approach to the Critically Ill Patient
Introduction
Critical care medicine specializes in caring for the most seriously ill patients. These patients are best
treated in an ICU staffed by experienced personnel. Some hospitals maintain separate units for special
populations (eg, cardiac, surgical, neurologic, pediatric, or neonatal patients). ICUs have a high
nurse:patient ratio to provide the necessary high intensity of service, including treatment and mon

Source 2 | Page: 2455
depending on patient characteristics). Poor outcomes often follow failure to institute early aggressive
therapy (eg, within 6 h of suspected diagnosis). Once severe lactic acidosis with decompensated
metabolic acidosis becomes established, especially in conjunction with multiorgan failure, septic shock is
likely to be irreversible and fatal.
Treatment
• Fluid resuscitation with 0.9% normal saline
• O2
• Broad-spectrum antibiotics (modified by culture results)
• Drainage of abscesses and excision

Source 3 | Page: 2456
Table 222-4 on p. 2248). Dosage is 24 μg/kg/h by continuous IV infusion for 96 h. Bleeding is the most
common complication; thus, contraindications include hemorrhagic stroke within 3 mo, spinal or
intracranial surgery within 2 mo, acute trauma with a risk of bleeding, and intracranial neoplasm. Risk-
benefit assessment is required in other patients with increased risk of serious bleeding (eg, with
thrombocytopenia or recent GI bleeding, receiving concurrent heparin, or with recent aspirin or ot

`Query 2: What are the common symptoms of appendicitis, and can it be cured via medicine? If not, what surgical procedure should be followed to treat it?`

In [ ]:
answer, retrieved_docs = generate_rag_response(
    query_2.replace("[INST]", "").replace("[/INST]", ""),
    k=3,
    max_tokens=350,
    temperature=0,
    top_p=0.95,
    top_k=50
)

print("RAG ANSWER:")
print(answer)

print("\nRETRIEVED SOURCES:")

for i, doc in enumerate(retrieved_docs, 1):

    print(
        f"\nSource {i} | "
        f"Page: {doc.metadata.get('page', 'N/A')}"
    )

    print(doc.page_content[:500])

Llama.generate: prefix-match hit

RAG ANSWER:
The common symptoms for appendicitis include epigastric or periumbilical pain followed by brief nausea, vomiting, and anorexia, which is later followed by pain shifting to the right lower quadrant. Pain increases with cough and motion. Classical signs are direct and rebound tenderness at McBurney's point, Rovsing sign, psoas sign, or obturator sign. A low-grade fever (rectal temperature 100 to 101°F) is common. Unfortunately, these classic findings appear in less than 50% of patients, and many variations of symptoms and signs occur. Appendicitis is typically treated with surgical removal, and if a perforation is noted, immediate surgery is necessary due to the risk of mortality from peritonitis increasing rapidly with delayed treatment. If an abscess or inflammatory mass has formed, the procedure may be limited to drainage of the abscess. Antibiotics and IV fluids are also administered for treatment. The surgical procedure followed to treat appendicitis is open or laparoscopic appendectomy. According to the provided context, there is no mention of a cure for appendicitis via medicine alone.

Source: Merck Manuals - Appendicitis (Section 11, Gastrointestinal System Disorders)

RETRIEVED SOURCES:

Source 1 | Page: 173
Etiology
Appendicitis is thought to result from obstruction of the appendiceal lumen, typically by lymphoid
hyperplasia, but occasionally by a fecalith, foreign body, or even worms. The obstruction leads to
distention, bacterial overgrowth, ischemia, and inflammation. If untreated, necrosis, gangrene, and
perforation occur. If the perforation is contained by the omentum, an appendiceal abscess results.
Symptoms and Signs
The classic symptoms of acute appendicitis are epigastric or periumbilical

Source 2 | Page: 172
nondiagnostic, abdominal CT usually with oral and IV and/or rectal contrast may be helpful. Barium
should not be used if perforation is suspected.
Treatment
• Surgery
• IV fluids and antibiotics
[Table 11-4. Some Causes of GI Tract Perforation]
If a perforation is noted, immediate surgery is necessary because mortality caused by peritonitis
increases rapidly the longer treatment is delayed. If an abscess or an inflammatory mass has formed, the
procedure may be limited to drainage of the abscess.

Source 3 | Page: 174
• Surgical removal
• IV fluids and antibiotics
Treatment of acute appendicitis is open or laparoscopic appendectomy; because treatment delay
increases mortality, a negative appendectomy rate of 15% is considered acceptable. The surgeon can
usually remove the appendix even if perforated. Occasionally, the appendix is difficult to locate: In these
cases, it usually lies behind the cecum or the ileum and mesentery of the right colon. A contraindication to
appendectomy is inflammatory bowel disease

`Query 3: What are the effective treatments or solutions for addressing sudden patchy hair loss, commonly seen as localized bald spots on the scalp, and what could be the possible causes behind it?`

In [ ]:
answer, retrieved_docs = generate_rag_response(
    query_3.replace("[INST]", "").replace("[/INST]", ""),
    k=3,
    max_tokens=350,
    temperature=0,
    top_p=0.95,
    top_k=50
)

print("RAG ANSWER:")
print(answer)

print("\nRETRIEVED SOURCES:")

for i, doc in enumerate(retrieved_docs, 1):

    print(
        f"\nSource {i} | "
        f"Page: {doc.metadata.get('page', 'N/A')}"
    )

    print(doc.page_content[:500])

Llama.generate: prefix-match hit

RAG ANSWER:
The context from the Merck Manuals indicates that sudden patchy hair loss, also known as alopecia areata, is a condition characterized by bald spots on the scalp or other hair-bearing areas with no obvious skin or systemic disorder. The causes of this condition are believed to be autoimmune in nature and may affect genetically susceptible individuals exposed to unclear environmental triggers.

Effective treatments for alopecia areata include:

1. Topical corticosteroids: These medications can help reduce inflammation and promote hair regrowth. They can be applied directly to the affected areas in various forms, such as foams, lotions, or solutions.
2. Intralesional corticosteroid injections: This treatment involves injecting corticosteroids directly into the affected area using a fine needle. It may provide more effective results than topical applications but can cause more side effects.
3. Topical minoxidil: This medication is applied to the scalp twice daily and has been shown to promote hair growth in some individuals with alopecia areata. However, it may take several months to see noticeable results.
4. Topical anthralin: This medication is a synthetic derivative of vitamin A that can help reduce inflammation and promote hair regrowth. It is applied to the affected areas once daily for several weeks before being tapered off.
5. Topical immunotherapy (diphencyprone or squaric acid dibutylester): This treatment involves applying an allergen to the affected area, which causes an allergic reaction that stimulates hair reg

RETRIEVED SOURCES:

Source 1 | Page: 858
• Concomitant virilization in women or scarring hair loss should prompt a thorough evaluation for the
underlying disorder.
• Microscopic hair examination or scalp biopsy may be required for definitive diagnosis.
Alopecia Areata
Alopecia areata is sudden patchy hair loss in people with no obvious skin or systemic disorder.
The scalp and beard are most frequently affected, but any hairy area may be involved. Hair loss may
affect most or all of the body (alopecia universalis). Alopecia areata is th

Source 2 | Page: 858
loss and can stimulate hair
[Table 86-2. Interpreting Findings in Alopecia]
growth. Efficacy is usually evident within 6 to 8 mo of treatment. Adverse effects include decreased libido,
erectile and ejaculatory dysfunction, hypersensitivity reactions, gynecomastia, and myopathy. There may
be a decrease in prostate-specific antigen levels in older men, which should be taken into account when
that test is used for cancer screening. Common practice is to continue treatment for as long as positive
re

Source 3 | Page: 855
Chapter 86. Hair Disorders
Introduction
Hair growth in both men and women is regulated by androgens. Testosterone stimulates hair growth in
the pubic area and underarms. Dihydrotestosterone stimulates beard hair growth and scalp hair loss.
Hair disorders include alopecia, hypertrichosis, hirsutism, and pseudofolliculitis barbae. Although most
hair disorders are not serious, they are often perceived as major cosmetic issues that demand treatment.
Dandruff is not a hair disorder but rather a skin

`Query 4: What treatments are recommended for a person who has sustained a physical injury to brain tissue, resulting in temporary or permanent impairment of brain function?`

In [ ]:
answer, retrieved_docs = generate_rag_response(
    query_4.replace("[INST]", "").replace("[/INST]", ""),
    k=3,
    max_tokens=350,
    temperature=0,
    top_p=0.95,
    top_k=50
)

print("RAG ANSWER:")
print(answer)

print("\nRETRIEVED SOURCES:")

for i, doc in enumerate(retrieved_docs, 1):

    print(
        f"\nSource {i} | "
        f"Page: {doc.metadata.get('page', 'N/A')}"
    )

    print(doc.page_content[:500])

Llama.generate: prefix-match hit

RAG ANSWER:
Based on the information from the Merck Manual, the following treatments are recommended for a person who has sustained a physical injury to brain tissue:

1. For mild injuries, discharge and observation are sufficient.
2. For moderate and severe injuries, optimization of ventilation, oxygenation, and brain perfusion is necessary. Treatment of complications such as increased intracranial pressure (ICP), seizures, and hematomas is also essential. Rehabilitation is recommended.
3. Initial resuscitation of trauma patients includes securing a clear airway, controlling external bleeding, avoiding displacement of the spine or other bones, and providing pain relief with a short-acting opioid.
4. For larger lesions, rapidly developing lesions, and lesions that affect both hemispheres, treatment focuses on managing symptoms and supporting overall health to promote recovery.
5. Recovery from brain injury depends on the plasticity of the remaining cerebrum, which varies from person to person and is affected by age and general health. Plasticity is most prominent in the developing brain, but significant recovery is still possible after the first decade of life. Gross reorganization of brain function after injury in adults is uncommon, although plasticity remains operative in certain specific areas of the brain throughout life.

Sources:
The Merck Manual of Diagnosis & Therapy, 19th Edition
Chapter 324. Traumatic Brain Injury
3398
shahanam04@gmail.com
UPWIKCV2H5

RETRIEVED SOURCES:

Source 1 | Page: 3407
recover normal neurologic function when a persistent vegetative state lasts for 3 mo after injury, and
almost none recover after 6 mo.
The Merck Manual of Diagnosis & Therapy, 19th Edition
Chapter 324. Traumatic Brain Injury
3398
shahanam04@gmail.com
UPWIKCV2H5
This file is meant for personal use by shahanam04@gmail.com only.
Sharing or publishing the contents in part or full is liable for legal action.

Source 2 | Page: 3409
regardless of severity and continue to improve for a longer period of time.
Cognitive deficits, with impaired concentration, attention, and memory, and various personality changes
are a more common cause of disability in social relations and employment than are focal motor or sensory
impairments. Posttraumatic anosmia and acute traumatic blindness seldom resolve after 3 to 4 mo.
Hemiparesis and aphasia usually resolve at least partially, except in the elderly.
Treatment
• For mild injuries disch

Source 3 | Page: 1814
Larger lesions, rapidly developing lesions (over weeks or months rather than years), and lesions that
simultaneously affect both hemispheres are more likely to become symptomatic. Focal lesions in white
matter can interrupt the connectivity between brain areas and cause the disconnection syndrome (inability
to do a task that requires coordinated activity of ≥ 2 brain regions, despite retention of basic functions of
each region).
Global dysfunction is caused by toxicmetabolic disorders or sometim

`Query 5: What are the necessary precautions and treatment steps for a person who has fractured their leg during a hiking trip, and what should be considered for their care and recovery?`

In [ ]:
answer, retrieved_docs = generate_rag_response(
    query_5.replace("[INST]", "").replace("[/INST]", ""),
    k=3,
    max_tokens=350,
    temperature=0,
    top_p=0.95,
    top_k=50
)

print("RAG ANSWER:")
print(answer)

print("\nRETRIEVED SOURCES:")

for i, doc in enumerate(retrieved_docs, 1):

    print(
        f"\nSource {i} | "
        f"Page: {doc.metadata.get('page', 'N/A')}"
    )

    print(doc.page_content[:500])

Llama.generate: prefix-match hit

RAG ANSWER:
Based on the information from the Merck Manuals, a person with a fractured leg (femoral shaft fracture) from a hiking incident should receive the following care:

1. Initial assessment and stabilization: In case of severe pain, swelling, deformity, or instability, immediate splinting is necessary to prevent further injury and decrease pain. Hemorrhagic shock, if present, should be treated in the emergency department.

2. Definitive treatment: ORIF (Open Reduction Internal Fixation) is typically used for femoral shaft fractures. This procedure involves surgically aligning and stabilizing the bone with plates or screws.

3. Rehabilitation: After surgery, rehabilitation should be initiated as soon as possible to increase strength, prevent atrophy on the unaffected side, and promote full ambulation. Initially, only isometric exercises are permitted while the affected limb is fully extended. Gradual mobilization will eventually lead to full ambulation.

4. Precautions: For patients with a lower-limb prosthesis, maintaining body alignment is essential. However, even with a good fit, skin breakdown can occur due to ongoing changes in stump size. If there are signs of skin breakdown, prompt consultation with a healthcare practitioner and prosthetist is recommended.

5. Pain management: Pain is typically treated with opioids.

Source: The Merck Manual of Diagnosis & Therapy, 19th Edition, Chapter 323. Fractures, Dislocations & Sprains.

RETRIEVED SOURCES:

Source 1 | Page: 3396
are usually diagnostic. Treatment is usually ORIF and early mobilization.
Femoral shaft fractures: The usual injury mechanism is severe direct force or an axial load to the flexed
knee. Fracture due to trauma causes obvious swelling, deformity, and instability. Up to 1.5 L of blood for
each fracture may be lost. Treatment is immediate splinting, then ORIF.
The Merck Manual of Diagnosis & Therapy, 19th Edition
Chapter 323. Fractures, Dislocations & Sprains
3387
shahanam04@gmail.com
UPWIKCV2H5
Thi

Source 2 | Page: 3390
(eg, meniscal tears, cartilaginous injuries). Arteriography may be necessary for suspected arterial injuries
(eg, some popliteal artery injuries). Nerve conduction studies may be indicated for nerve injuries.
Treatment
• Treatment of life- or limb-threatening injuries
• Splinting
• Definitive treatment (eg, reduction) for certain injuries
• Rest, ice, compression, and elevation (RICE)
• Usually immobilization
In the emergency department, hemorrhagic shock is treated. Injuries to arteries are rep

Source 3 | Page: 3646
• For patients with a lower-limb prosthesis, maintaining body alignment (eg, wearing only shoes with a
similar heel height)
However, even with a good fit, problems can occur. The stump changes in shape and size throughout a
day, depending on activity level, diet, and the weather. Thus, there are times when the interface fits well
and times when it fits less well. In response to such ongoing changes, people can help maintain a good fit
by switching to a thicker or thinner liner or sock, by using

**Observation:**

The generated response integrates this evidence into a structured treatment overview while noting variability in patient outcomes.

**Overall insight:** All the outputs shows the strength of RAG in medical decision-support:

It reduces information overload by surfacing the most relevant passages.

It improves traceability by exposing page references.

It balances concise AI-generated summaries with authoritative source material, ensuring clinicians can verify and contextualize recommendations.

In short, RAG makes the output more reliable, transparent, and clinically useful than a standalone LLM response.

###**Fine-tuning**

Fine-tune the retriever, and LLM parameters (at least 5 combinations) to check different results.

In [ ]:
rag_configurations = [
    {
        "name": "RAG Configuration 1",
        "k": 2,
        "temperature": 0,
        "top_p": 0.90,
        "top_k": 40,
        "max_tokens": 300
    },

    {
        "name": "RAG Configuration 2",
        "k": 3,
        "temperature": 0,
        "top_p": 0.95,
        "top_k": 50,
        "max_tokens": 350
    },

    {
        "name": "RAG Configuration 3",
        "k": 4,
        "temperature": 0.1,
        "top_p": 0.90,
        "top_k": 40,
        "max_tokens": 400
    },

    {
        "name": "RAG Configuration 4",
        "k": 5,
        "temperature": 0.2,
        "top_p": 0.90,
        "top_k": 50,
        "max_tokens": 450
    },

    {
        "name": "RAG Configuration 5",
        "k": 6,
        "temperature": 0,
        "top_p": 0.85,
        "top_k": 30,
        "max_tokens": 500
    }
]

In [ ]:
rag_experiment_results = []

clean_questions = [
    query_1.replace("[INST]", "").replace("[/INST]", ""),
    query_2.replace("[INST]", "").replace("[/INST]", ""),
    query_3.replace("[INST]", "").replace("[/INST]", ""),
    query_4.replace("[INST]", "").replace("[/INST]", ""),
    query_5.replace("[INST]", "").replace("[/INST]", "")
]

for config in rag_configurations:

    for question_number, question in enumerate(
        clean_questions,
        1
    ):

        answer, retrieved_docs = generate_rag_response(
            question,
            k=config["k"],
            max_tokens=config["max_tokens"],
            temperature=config["temperature"],
            top_p=config["top_p"],
            top_k=config["top_k"]
        )

        rag_experiment_results.append({
            "Configuration": config["name"],
            "Question": question_number,
            "K": config["k"],
            "Temperature": config["temperature"],
            "Top_P": config["top_p"],
            "Top_K": config["top_k"],
            "Answer": answer
        })

rag_results_df = pd.DataFrame(
    rag_experiment_results
)

rag_results_df

Llama.generate: prefix-match hit
Llama.generate: prefix-match hit
Llama.generate: prefix-match hit
Llama.generate: prefix-match hit
Llama.generate: prefix-match hit
Llama.generate: prefix-match hit
Llama.generate: prefix-match hit
Llama.generate: prefix-match hit
Llama.generate: prefix-match hit
Llama.generate: prefix-match hit
Llama.generate: prefix-match hit
Llama.generate: prefix-match hit
Llama.generate: prefix-match hit
Llama.generate: prefix-match hit
Llama.generate: prefix-match hit
Llama.generate: prefix-match hit
Llama.generate: prefix-match hit
Llama.generate: prefix-match hit
Llama.generate: prefix-match hit
Llama.generate: prefix-match hit
Llama.generate: prefix-match hit
Llama.generate: prefix-match hit
Llama.generate: prefix-match hit
Llama.generate: prefix-match hit
Llama.generate: prefix-match hit

,Configuration,Question,K,Temperature,Top_P,Top_K,Answer
0,RAG Configuration 1,1,2,0.0,0.90,40,The protocol for managing sepsis in a critical...
1,RAG Configuration 1,2,2,0.0,0.90,40,The common symptoms for appendicitis include e...
2,RAG Configuration 1,3,2,0.0,0.90,40,The context from the Merck Manuals indicates t...
3,RAG Configuration 1,4,2,0.0,0.90,40,Based on the information from the Merck Manual...
4,RAG Configuration 1,5,2,0.0,0.90,40,Based on the information from the Merck Manual...
5,RAG Configuration 2,1,3,0.0,0.95,50,The protocol for managing sepsis in a critical...
6,RAG Configuration 2,2,3,0.0,0.95,50,The common symptoms for appendicitis include e...
7,RAG Configuration 2,3,3,0.0,0.95,50,The context from the Merck Manuals indicates t...
8,RAG Configuration 2,4,3,0.0,0.95,50,Based on the information from the Merck Manual...
9,RAG Configuration 2,5,3,0.0,0.95,50,Based on the information from the Merck Manual...
10,RAG Configuration 3,1,4,0.1,0.90,40,The protocol for managing sepsis in a critical...
11,RAG Configuration 3,2,4,0.1,0.90,40,The common symptoms for appendicitis include e...
12,RAG Configuration 3,3,4,0.1,0.90,40,The context from the Merck Manuals indicates t...
13,RAG Configuration 3,4,4,0.1,0.90,40,Based on the information from the Merck Manual...
14,RAG Configuration 3,5,4,0.1,0.90,40,Based on the information from the Merck Manual...
15,RAG Configuration 4,1,5,0.2,0.90,50,The protocol for managing sepsis in a critical...
16,RAG Configuration 4,2,5,0.2,0.90,50,The common symptoms for appendicitis include e...
17,RAG Configuration 4,3,5,0.2,0.90,50,The context from the Merck Manuals indicates t...
18,RAG Configuration 4,4,5,0.2,0.90,50,Based on the information from the Merck Manual...
19,RAG Configuration 4,5,5,0.2,0.90,50,"Based on the information in the Merck Manual, ..."
20,RAG Configuration 5,1,6,0.0,0.85,30,The protocol for managing sepsis in a critical...
21,RAG Configuration 5,2,6,0.0,0.85,30,The common symptoms for appendicitis include e...
22,RAG Configuration 5,3,6,0.0,0.85,30,The context from the Merck Manuals indicates t...
23,RAG Configuration 5,4,6,0.0,0.85,30,Based on the information from the Merck Manual...
24,RAG Configuration 5,5,6,0.0,0.85,30,Based on the information from the Merck Manual...

**Observations:**

The RAG experiments demonstrate that both retrieval and generation parameters influence answer quality. A lower k produces a more focused context but may omit information when the answer spans multiple sections.

Increasing k can improve information coverage but may also introduce irrelevant passages. Lower temperature values generally produce more deterministic responses, which is preferable for medical information retrieval. The final configuration should be selected based on the groundedness and relevance evaluation rather than response length alone.

###**Output Evaluation**

We are using the same Mistral model for evaluation with improved prompts.

**Groundedness evaluator**

In [ ]:
groundedness_rater_system_message = """
You are an evaluator for a medical Retrieval-Augmented Generation system.

Your task is to evaluate the GROUNDEDNESS of the generated answer.

Groundedness means whether the claims made in the answer are supported
by the retrieved context from the Merck Manuals.

Use this scoring scale:

5 = Fully grounded. All important claims are supported by the context.
4 = Mostly grounded. Most claims are supported, with minor unsupported details.
3 = Partially grounded. Some important claims are supported, but others are not.
2 = Mostly ungrounded. Only a small portion is supported.
1 = Ungrounded. The answer is not supported by the provided context.

Do not judge whether the answer is medically correct in general.
Judge only whether it is supported by the supplied context.

Return:
Score: <1-5>
Reason: <brief explanation>
"""

**Relevance evaluator**

In [ ]:
relevance_rater_system_message = """
You are an evaluator for a medical question-answering system.

Your task is to evaluate the RELEVANCE of the generated answer.

Relevance means whether the answer directly addresses the user's question
and covers the major aspects requested.

Use this scoring scale:

5 = Fully relevant and complete.
4 = Mostly relevant with minor omissions.
3 = Partially relevant; some important aspects are missing.
2 = Mostly irrelevant or incomplete.
1 = Completely irrelevant.

Return:
Score: <1-5>
Reason: <brief explanation>
"""

**User message template**

In [ ]:
user_message_template = """
QUESTION:
{question}

RETRIEVED CONTEXT:
{context}

GENERATED ANSWER:
{answer}

Evaluate the generated answer according to your assigned evaluation criterion.
"""

**Evaluation function**

In [ ]:
def generate_ground_relevance_response(
    user_input,
    k=3,
    max_tokens=200,
    temperature=0,
    top_p=0.95,
    top_k=50
):

    # Retrieve documents
    relevant_document_chunks = retriever.invoke(
        user_input
    )[:k]

    context_for_query = "\n\n".join(
        [d.page_content for d in relevant_document_chunks]
    )

    # Generate RAG answer
    qna_prompt = f"""[INST]
{qna_system_message}

{qna_user_message_template.format(
    context=context_for_query,
    question=user_input
)}
[/INST]"""

    answer_response = llm(
        prompt=qna_prompt,
        max_tokens=max_tokens,
        temperature=temperature,
        top_p=top_p,
        top_k=top_k
    )

    answer = answer_response[
        "choices"
    ][0]["text"].strip()

    # Groundedness evaluation
    groundedness_prompt = f"""[INST]
{groundedness_rater_system_message}

{user_message_template.format(
    context=context_for_query,
    question=user_input,
    answer=answer
)}
[/INST]"""

    groundedness_response = llm(
        prompt=groundedness_prompt,
        max_tokens=200,
        temperature=0,
        top_p=0.95,
        top_k=50
    )

    # Relevance evaluation
    relevance_prompt = f"""[INST]
{relevance_rater_system_message}

{user_message_template.format(
    context=context_for_query,
    question=user_input,
    answer=answer
)}
[/INST]"""

    relevance_response = llm(
        prompt=relevance_prompt,
        max_tokens=200,
        temperature=0,
        top_p=0.95,
        top_k=50
    )

    groundedness = groundedness_response[
        "choices"
    ][0]["text"].strip()

    relevance = relevance_response[
        "choices"
    ][0]["text"].strip()

    return answer, groundedness, relevance

###**Evaluation Queries**

`Query 1: What is the protocol for managing sepsis in a critical care unit?`

In [ ]:
answer, groundedness, relevance = generate_ground_relevance_response(
    clean_questions[0],
    k=3
)

print("ANSWER")
print(answer)

print("\nGROUNDEDNESS EVALUATION")
print(groundedness)

print("\nRELEVANCE EVALUATION")
print(relevance)

Llama.generate: prefix-match hit
Llama.generate: prefix-match hit
Llama.generate: prefix-match hit

ANSWER
The protocol for managing sepsis in a critical care unit includes the following steps:

1. Fluid resuscitation with 0.9% normal saline until central venous pressure (CVP) reaches 8 mm Hg (10 cm H2O) or pulmonary artery occlusive pressure (PAOP) reaches 12 to 15 mm Hg. Oliguria with hypotension is not a contraindication to vigorous fluid resuscitation.
2. Administration of oxygen.
3. Broad-spectrum antibiotics, modified by culture results.
4. Drainage of abscesses and excision of necrotic tissue.
5. Normalization of blood glucose levels.
6. Replacement-dose corticosteroids (24 μg/kg/h by continuous IV infusion for 96 hours). However, contraind

GROUNDEDNESS EVALUATION
Score: 5
Reason: The generated answer fully matches the retrieved context in terms of the steps involved in managing sepsis in a critical care unit. All important claims are supported by the context.

RELEVANCE EVALUATION
Score: 5
Reason: The generated answer directly addresses the user's question and covers all the major aspects requested about managing sepsis in a critical care unit, including fluid resuscitation, oxygen administration, broad-spectrum antibiotics, drainage of abscesses and excision of necrotic tissue, normalization of blood glucose levels, and replacement-dose corticosteroids.

`Query 2: What are the common symptoms for appendicitis, and can it be cured via medicine? If not, what surgical procedure should be followed to treat it?`

In [ ]:
answer, groundedness, relevance = generate_ground_relevance_response(
    clean_questions[1],
    k=3
)

print("ANSWER")
print(answer)

print("\nGROUNDEDNESS EVALUATION")
print(groundedness)

print("\nRELEVANCE EVALUATION")
print(relevance)

Llama.generate: prefix-match hit
Llama.generate: prefix-match hit
Llama.generate: prefix-match hit

ANSWER
The common symptoms for appendicitis include epigastric or periumbilical pain followed by brief nausea, vomiting, and anorexia, which is then followed by pain shifting to the right lower quadrant. Pain increases with cough and motion. Classic signs are direct and rebound tenderness located at McBurney's point, Rovsing sign, psoas sign, or obturator sign. A low-grade fever (rectal temperature 100 to 101°F) is common. Unfortunately, these classic findings appear in less than 50% of patients, and many variations of symptoms and signs occur. Appendicitis is typically treated with surgical removal, specifically open or laparoscopic appendectomy. If a perforation is noted, immediate surgery is necessary due to the risk of mortality from peritonitis increasing rapidly with delayed treatment. Antibiotics and IV fluids

GROUNDEDNESS EVALUATION
Score: 5
Reason: The generated answer accurately and fully conveys the common symptoms for appendicitis as described in the context, including epigastric or periumbilical pain, nausea, vomiting, anorexia, shifting pain to the right lower quadrant, and various signs of tenderness. It also correctly states that surgical removal is the typical treatment for appendicitis and mentions the use of antibiotics and IV fluids when necessary. The answer fully reflects the information in the context.

RELEVANCE EVALUATION
Score: 5
Reason: The generated answer fully addresses the user's question by providing a detailed explanation of the common symptoms for appendicitis and the treatment options, including surgical removal and antibiotics. It covers all the major aspects requested in the question.

`Query 3: What are the effective treatments or solutions for addressing sudden patchy hair loss, commonly seen as localized bald spots on the scalp, and what could be the possible causes behind it?`

In [ ]:
answer, groundedness, relevance = generate_ground_relevance_response(
    clean_questions[2],
    k=3
)

print("ANSWER")
print(answer)

print("\nGROUNDEDNESS EVALUATION")
print(groundedness)

print("\nRELEVANCE EVALUATION")
print(relevance)

Llama.generate: prefix-match hit
Llama.generate: prefix-match hit
Llama.generate: prefix-match hit

ANSWER
The context from the Merck Manuals indicates that sudden patchy hair loss, also known as alopecia areata, is a condition characterized by bald spots on the scalp or any other hair-bearing area. This condition affects people with no obvious skin or systemic disorder. Alopecia areata is believed to be an autoimmune disorder and may be triggered by unclear environmental factors.

The effective treatments for addressing sudden patchy hair loss include:

1. Topical corticosteroids: These medications can help reduce inflammation and promote hair regrowth. They can be applied directly to the affected area.
2. Intralesional corticosteroid injections: Corticosteroids can also be injected into the affected area for more effective treatment.
3. Topical minoxidil: This medication can stimulate hair growth and may be applied twice daily to the affected area.
4. Topical anth

GROUNDEDNESS EVALUATION
Score: 5
Reason: The generated answer accurately summarizes the information from the context regarding sudden patchy hair loss, its possible causes as an autoimmune disorder, and effective treatments such as topical corticosteroids, intralesional corticosteroid injections, and topical minoxidil.

RELEVANCE EVALUATION
Score: 5
Reason: The generated answer directly addresses the user's question by providing a clear explanation of what alopecia areata is, its causes, and effective treatments for addressing sudden patchy hair loss. It covers all the major aspects requested in the question.

`Query 4: What treatments are recommended for a person who has sustained a physical injury to brain tissue, resulting in temporary or permanent impairment of brain function?`

In [ ]:
answer, groundedness, relevance = generate_ground_relevance_response(
    clean_questions[3],
    k=3
)

print("ANSWER")
print(answer)

print("\nGROUNDEDNESS EVALUATION")
print(groundedness)

print("\nRELEVANCE EVALUATION")
print(relevance)

Llama.generate: prefix-match hit
Llama.generate: prefix-match hit
Llama.generate: prefix-match hit

ANSWER
Based on the information from the Merck Manual, the following treatments are recommended for a person who has sustained a physical injury to brain tissue:

1. For mild injuries, discharge and observation are sufficient.
2. For moderate and severe injuries, optimization of ventilation, oxygenation, and brain perfusion is necessary. Treatment of complications such as increased intracranial pressure (ICP), seizures, and hematomas is also essential. Rehabilitation is recommended.
3. Initial resuscitation of trauma patients includes securing a clear airway, controlling external bleeding, avoiding displacement of the spine or other bones, and providing pain relief with a short-acting opioid.
4. For larger lesions, rapidly developing lesions, and lesions that affect both hemispheres, treatment focuses on managing symptoms and supporting overall health to promote recovery.
5. Recovery from brain injury depends on the plasticity of the

GROUNDEDNESS EVALUATION
Score: 5
Reason: The generated answer fully grounds all the recommended treatments for a person with a physical injury to brain tissue based on the provided context from the Merck Manual.

RELEVANCE EVALUATION
Score: 5
Reason: The generated answer directly addresses the user's question by summarizing the treatments recommended for a person who has sustained a physical injury to brain tissue, based on the provided context from the Merck Manual. It covers all the major aspects requested in the question.

`Query 5: What are the necessary precautions and treatment steps for a person who has fractured their leg during a hiking trip, and what should be considered for their care and recovery?`

In [ ]:
answer, groundedness, relevance = generate_ground_relevance_response(
    clean_questions[4],
    k=3
)

print("ANSWER")
print(answer)

print("\nGROUNDEDNESS EVALUATION")
print(groundedness)

print("\nRELEVANCE EVALUATION")
print(relevance)

Llama.generate: prefix-match hit
Llama.generate: prefix-match hit
Llama.generate: prefix-match hit

ANSWER
Based on the information from the Merck Manuals, a person with a fractured leg (femoral shaft fracture) from a hiking incident should receive the following care:

1. Initial assessment and stabilization: In case of severe pain, swelling, deformity, or instability, immediate splinting is necessary to prevent further injury and decrease pain. Hemorrhagic shock, if present, should be treated in the emergency department with fluid resuscitation and surgical repair for life- or limb-threatening injuries.

2. Definitive treatment: Open reduction with internal fixation (ORIF) is typically used to realign the fractured bone. Early mobilization is essential for optimal recovery.

3. Precautions during transport: If necessary, the person should be transported carefully to ensure that the fracture remains stable and does not cause further harm.

4. Rehabilitation: After surgery,

GROUNDEDNESS EVALUATION
Score: 5
Reason: The generated answer fully grounds all important claims with the context from the Merck Manuals. It accurately summarizes the necessary precautions and treatment steps for a person with a fractured leg, including initial assessment and stabilization, definitive treatment (ORIF), and rehabilitation.

RELEVANCE EVALUATION
Score: 5
Reason: The generated answer directly addresses the user's question by providing a detailed explanation of the necessary precautions and treatment steps for a person with a fractured leg, covering all major aspects requested.

**Observation:**

The RAG answer shows strong alignment between retrieved Merck Manual content and the generated response. It clearly outlines initial stabilization, definitive treatment, transport precautions and rehabilitation steps.

The groundedness score of 5 reflects that all claims are supported by authoritative source material, while the relevance score of 5 confirms the response directly addresses the clinical scenario posed.

**Overall insight:** This example highlights how RAG can deliver clinically accurate, traceable, and context‑specific guidance. It balances concise decision‑support with transparency, ensuring healthcare professionals can verify the recommendations against trusted references.

###**consolidated evaluation table to make notebook much stronger**

In [ ]:
evaluation_results = []

for i, question in enumerate(clean_questions, 1):

    answer, groundedness, relevance = (
        generate_ground_relevance_response(
            question,
            k=3
        )
    )

    evaluation_results.append({
        "Question": i,
        "Answer": answer,
        "Groundedness Evaluation": groundedness,
        "Relevance Evaluation": relevance
    })

evaluation_df = pd.DataFrame(
    evaluation_results
)

evaluation_df

Llama.generate: prefix-match hit
Llama.generate: prefix-match hit
Llama.generate: prefix-match hit
Llama.generate: prefix-match hit
Llama.generate: prefix-match hit
Llama.generate: prefix-match hit
Llama.generate: prefix-match hit
Llama.generate: prefix-match hit
Llama.generate: prefix-match hit
Llama.generate: prefix-match hit
Llama.generate: prefix-match hit
Llama.generate: prefix-match hit
Llama.generate: prefix-match hit
Llama.generate: prefix-match hit
Llama.generate: prefix-match hit

,Question,Answer,Groundedness Evaluation,Relevance Evaluation
0,1,The protocol for managing sepsis in a critical...,Score: 5\nReason: The generated answer fully m...,Score: 5\nReason: The generated answer directl...
1,2,The common symptoms for appendicitis include e...,Score: 5\nReason: The generated answer accurat...,Score: 5\nReason: The generated answer fully a...
2,3,The context from the Merck Manuals indicates t...,Score: 5\nReason: The generated answer accurat...,Score: 5\nReason: The generated answer directl...
3,4,Based on the information from the Merck Manual...,Score: 5\nReason: The generated answer fully g...,Score: 5\nReason: The generated answer directl...
4,5,Based on the information from the Merck Manual...,Score: 5\nReason: The generated answer fully g...,Score: 5\nReason: The generated answer directl...

**Observations**

**Groundedness:** The groundedness evaluation measures whether the generated answer is supported by the retrieved Merck Manual context. Higher scores indicate that the RAG pipeline is successfully restricting the answer to information retrieved from the knowledge base. Lower scores indicate either retrieval problems or generation of information that was not present in the retrieved context.

**Relevance:** The relevance evaluation measures whether the generated answer addresses the user's question. A high relevance score indicates that the retrieved context and generation process are collectively addressing the requested medical topic.

**Overall:** The evaluation demonstrates the importance of both retrieval quality and generation quality. A response can be relevant but insufficiently grounded if the model introduces information beyond the retrieved context. Conversely, an answer can be well grounded but incomplete if the retriever fails to retrieve all the information required to answer the question.

##**Actionable Insights and Business Recommendations**

**Reduce information overload**  
Semantic retrieval from a large medical knowledge base minimizes the need for clinicians to manually search thousands of pages, streamlining access to critical information.

**Enhance decision‑support efficiency**  
Relevant passages can be retrieved in seconds and paired with concise AI‑generated summaries, cutting down the time required to locate and interpret reference material.

**Improve transparency and traceability**  
Unlike standalone LLMs, the RAG system exposes the retrieved Merck Manual passages and page metadata. This allows healthcare professionals to verify the source material behind each response.

**Standardize access to medical knowledge**  
A centralized retrieval interface ensures consistent access to approved medical resources, supporting standardized practices across healthcare teams.

**Optimize retrieval and generation parameters**  
Experiments show that parameters such as the number of retrieved chunks (k), temperature, top‑p, and top‑k directly affect response quality. Configurations should be tuned for groundedness and relevance, not just response length.

**Maintain human oversight**  
The system is positioned as a decision‑support tool, not an autonomous diagnostic engine. Clinicians must validate AI‑generated insights against authoritative sources and patient‑specific circumstances.

**Keep the knowledge base current**  
The vector database should be refreshed whenever medical manuals or approved resources are updated, ensuring retrieval reflects the latest information without retraining the language model.

**Focus on information retrieval as the core use case**  
The strongest business value lies in rapid retrieval and summarization of trusted medical knowledge, helping clinicians manage information overload while maintaining a clear link to the underlying reference material.

###**Overall Conclusion:**

The project demonstrates the progression from a standalone LLM to a prompt-engineered LLM and finally to a Retrieval-Augmented Generation system using the Merck Manuals as the domain knowledge source.

The baseline LLM can generate medically relevant responses, but its answers lack source traceability. Prompt engineering improves structure, consistency and completeness.

The RAG approach further improves the system by retrieving relevant medical information from the supplied knowledge base before generating the answer. Groundedness and relevance evaluation provide a mechanism for comparing configurations and identifying potential weaknesses in retrieval or generation.

The proposed solution can therefore serve as a prototype for a healthcare knowledge-assistance platform, provided that appropriate human oversight, source validation, privacy controls and clinical governance are maintained.

**Thank You!**

In [ ]:
!jupyter nbconvert --to html Natural_Language_Processing_with_Generative_AI_Project.ipynb

[NbConvertApp] Converting notebook Natural_Language_Processing_with_Generative_AI_Project.ipynb to html
[NbConvertApp] Writing 691326 bytes to Natural_Language_Processing_with_Generative_AI_Project.html